apiVersion: v2
name: keycloak
version: 1.0.0
dependencies:
- name: postgresql
  version: 16.5.4
  repository: https://charts.bitnami.com/bitnami
- name: keycloak
  version: 24.4.13
  repository: https://charts.bitnami.com/bitnami