fullnameOverride: postgresql
architecture: standalone
auth:
  username: keycloak  
  database: keycloak
  existingSecret: keycloak-secret
  secretKeys:
    adminPasswordKey: postgresql-admin-password
    userPasswordKey: postgresql-password
    replicationPasswordKey: postgresql-replication-password
primary:    
  nodeSelector: 
    kubernetes.io/hostname: node1
  persistence:
    size: 1Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 750m
      memory: 768Mi