apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-ui
  namespace: ory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos-ui
  template:
    metadata:
      labels:
        app: kratos-ui
    spec:
      containers:
      - name: kratos-ui
        image: oryd/kratos-selfservice-ui-node:latest
        env:
        - name: KRATOS_PUBLIC_URL
          value: "https://kratos.example.com/"  # Địa chỉ public API của Kratos
        - name: KRATOS_BROWSER_URL
          value: "https://kratos-ui.example.com/"  # URL của giao diện UI
        ports:
        - containerPort: 3000