apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accounts-ingress
  namespace: ory
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  rules:
  - host: accounts.ecoma.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: accounts-service
            port:
              number: 80
  tls:
  - hosts:
      - accounts.ecoma.io
    secretName: accounts-tls
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: ory
spec:
  selector:
    app: accounts-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-site
  namespace: ory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-site
  template:
    metadata:
      labels:
        app: accounts-site
    spec:
      containers:
      - name: accounts-site
        image: oryd/kratos-selfservice-ui-node:latest
        env:
        - name: KRATOS_PUBLIC_URL
          value: kratos-public.ory.svc.cluster.local
        - name: KRATOS_PUBLIC_URL
          value: kratos-admin.ory.svc.cluster.local
        - name: COOKIE_SECRET          
          valueFrom:
            secretKeyRef:
              name: accounts-site-secret        
              key: secretsCookie
        - name: CSRF_COOKIE_NAME          
          valueFrom:
            secretKeyRef:
              name: accounts-site-secret        
              key: secretsCookie
        - name: CSRF_COOKIE_SECRET          
          valueFrom:
            secretKeyRef:
              name: accounts-site-secret        
              key: secretsCsrfCookie
        ports:
        - containerPort: 3000

