---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ory
spec:
  encryptedData:
    admin-password: AQBE4ZlaFBn/hZyu/N9M9I0B1tdMrgQjwrjtDXV1p6jCRJC4WPH2OpWk2lpYKQIT5RgpHbRjwiScsPLKF6SFNOKTN33hr8ZuSEcMSOVorHSjhx80B0usWq9+SFUPRFmXWOmV9SRd07MSEFB+L5T+lPMVTHa7OdsLnWNF3RUgP+MfPIB+Z+/qWxH2VHQUoFtwniRNw9vIQEAMoDxF3Eoh1PsGx4Vc6+pmbEEIbUQzCJuarZSeYsW2F07KLdRpEWwRDaPo0UlzA/wWghFy1vCr4QeA8LG4zr/ow97AAb7oybYa7XXN3d0zPa/Oo0yvWsgXKDoSpHgw9+dOxN9GHpC2hZlWDrpNo9ubhsgPIw/NbJAzIjN2ESiJjwxCL/8aRZ4FNPNhrLdgq/OwNjTMY851pWt8vLWXRg==
    password: AQAqBWjWMlANR9NJLzwr+V7cWyNaGRhdiwHAPjPi0jcYA4IBMpL0nLUx8NumH8zGzU51yoSDjoHQYIUj/Btl9RKWPqxzBX36rdP+h35/PupZzI5Td8mD3Z+t+cQJNJvc/9Jc7jdgO9a/WpVUQ9gmyAKvmH4XR7IDeqHaEVkjMVvqk01OW5t9TJHfAa4VMro9l6F4akyNFnIJejuRNRjPHiVKBW9BjmWWEioS7WXgKDArfGWefCuBmsRsv6JmTmdlOA4KUnqFjf0Y+3JlFdPYlmz+YnHQREzPSh6t+i8raO7fpUGQx+jlmEV4hiZ2GsI1Ikwpbv9W606VoaHIx61/mZQvozBmkNYF3GdYELiab7oVUFfMtyzhnRlVu29fbWFfbUgnfWibeyKZH64EEuga82gW1aAj9g==
    replication-password: AQARYzMaJP9on8+jARWq4fwKr8EP19dtKPiVngQR+p9jP+mAtDObx0n3n/ElsQHWEE8fjPoMn3xXdGhwNj3Kf5UNcY9uLCmJueGrm4qN8+q9+ml8u2h0XQ9HZ7H36eQIL1Zd08sfqIaLw1+OkhZnygSYBLlZwbe0BcOJiJ3WQOJbLiT6TOxwQfTQB5Rv8yHS8RhvPthbVBlBNLzWf6J+4p62YjlBKMJ8sDXqtMPowBPlUcAmBgjb1JUj/HG+oBBnfmcnihvEeLFjF2JfJDhYI35AGskD6DF3L0gSoPckFR3xOi/ZILavm7CpZbdmYHrqJKU7z5mbsZSJiEnyLqtLbb38IKHagDC5QYvDRNhSg+j0Z18GzZX0VlxDxkk2rCDbZqbegOnijgNdvU8brmP0tlLFb8eOKQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: ory

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kratos-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQBFm2H7cHXPA1A9kRM25pZ7BmmtYyJm49+ZAx8nxiobU1gJBfgmJowks78cnE50FPrljCoq8ynsp470eiVYDHorg1Jo31rwiPVpHO6odXQHg3WgYDIFGEIGm/rspjTGrFPTWD97Oc/Kba8Hak8t+duRAJ7M+F8IEdrNShnM3uwlRQtdzoCp3EFix7RU5Q4xMvxJNV06QveJA+qA3EVwtv8WMOpQrGRxt1sc5NWi1V+TApN4LN3+EoSZxqK8mKWdv70R0nHx3ei+A0Y1R3iP0gsC+SU0uz1++CMG4iDMZBPn/VM/BYAMF5oGGvWcWEfd0pEegjjw73ZTpAm32ZMoK91RpgPgJWCPYuazN6vCJAxXiNazPKwGWdO6YW9rZGVxAcueE/pq9mYY8Yfr+Lrvqj1GY5b7RhjEWDtFFLmFE7KhfILFjbKvtDPcoEvXdt/o7jRJnCHPxO7A8hi1sfPsVB2jcjr9j19caTFSojzwRoE=
    secretsCipher: AQAOMT9SOhtRJFv1q3fASRadTOd9F0vN0xWPqj5Or91WXeIHhHct+x+BsW3uBGuomdnizogpS+iWl+9mXQ55OHDgvbExihZjtSzirLnFk2q37VYH9CgNjxsSio7g448zZAJvGGuV1yWVAB4rgiE2bcAFz96wCSI1exlm6msSFAkBBy45QVH38bJvknlvkefEg+s0aIR+DUcUmP3SZBahOEIhxMn3+93WUCZhkUzmnC+zNmpeNzHVPMrZfGxHVVHvFgkS2S8tdXSzMocDSCkmLdNbvsaillUdhXZaKCDPX360kLFZHfV6M5L5fkdgWGveQid9ev9h1C7qz9HbxgxrVKPX7xZIRhTHySkjouyEl6EHDnKLOzKPgB1KlbopwOlS1mUUHwwD1itBgGEQGZ1eezB9
    secretsCookie: AQBpLOFgBFiHOmPoIgILf8M3JSQdLK/mAnZtAjSkzEBqECSa7+06kxMFAHVZjblDjT9MeTOJWkduIv6QTeAZWa0L1AygzDL8DVuySTM40FeWwhaK4SIW3yM//2b/Euv4M1mwF/X5Hhnz7D47bAPY44TlzXs6ihkEgcmJsqgeZEKW9KgEIHtWqdb58Y+N0wwSvqi26epz8VlpPRioN/bsMPIkwajdef4mMNbyteKAkgjYK2jvlHz146gPCkm+O9u8fmrIkhZPLYvjZLXqqHLueFeXLoSjZecB6sp+CveW18z5srpJRdGqIQR2VBWcTS5yr+peiF8gVb70DQHVrKPKLxJLpUXa/30LZ/iiTEZ3RhHAGQOqJMLVPO10LMwsxpJDRLeNF61rQXrZ3+w/TOlSyjis
    secretsDefault: AQBAHNzSpR7cOVY3PVQhEdxKrslg1OOk25c3JBWl93hmqJg8kaEN6hXzG2FiKqWFJUKd+g+naJ6nxFpI1pOQyrT+Y3u3KYK8+CuNY0fxn8qTiWFbkjqCiYlHm8nw90w+BHS5JCS+zuXxdzGA9dxi6Xu7I39ELB1YeuaNGaBrj3R7ndQDmXxh7d02wivJT34w+Dp+894V/pg766ff4Rf4xmT8LilOgxS38z54YrSj7XsRA8ThgOxWoV7LLX0y5GRkFT+a3nIEpYD+zaA7S7NWmxvv1Ab0Zi4q7ZunSYOu4QxDh+p/eOJraaOeaOwxf3PUGbYpPwP1nQvvEzT6jW7j1oOectCVzeidiR/7m18GtYUbQi4tWX/nacspEYbfuvDxmM+eOgClF19kuStZ7/A7eM1l
    smtpConnectionURI: AQBpNlkFnIhL0HzQxt/bXGX3oLIVQyGMDHGShOYV72rcgDYQMF3qwsOjvltRiz3yFgII6guZz6WkmsCPz+SvfIlz7sJBxLNlASGbzPkknJAXZd1hVOazeFntDRufcdaqaI/PmSz38dO959wliONoVUxmwQ5bXVI6u2J+IekvAU/WDrBn1XLeOZwQPj65bpVUmJJ3nfdqI7xyW7Hr2ek4th2+w9wT0ajH2HyyfsBnm4bvZmdeen1IFEcdikFQ/ISM+wGQFOPT5qXMRIMaSE+P/UY0sdU1NZl40hlv2DFCRqHoos/t5ZjgR0usasbNye0ljB+6NCYWg+UPKrLE2m4iedENdEBnIpR7jGKPyh09EEaq/NVCQQV6bBcH2cAAodSGpaVGtfnTcpqdkaBRsamguznrQawM8EM5OocsUGUFzenXkeWXyf4CYaedYQ==
  template:
    metadata:
      creationTimestamp: null
      name: kratos-secret
      namespace: ory

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hydra-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQB9ZU65qjfE/gOSZaly5uV1MQ1UKBa4iCVSh5Huno4LZspQQaUsM+FGhmg+n2UECQAgrG314KwqOy+31Fq76DVsQkYTIcnpjq/vQKvtU8GxXEbdgdx0XS3ndb0TWzYik+mLK1W/bdy+ep1FAZxWv6b6+xdAtJMwEqJIe4fJQZlVuGotBH69SgA+DwOxlgcHWClu2RbpA3Af8HVrOJP9PkQ5SCTJGNhix+dRJ3UvcRWlp5aGJrxsrPI+QaONLZj+VW3vylB+6GnWzVFTcfJxbeQznztVCb2G+YlxMlJOkANc46n4jOZi22J7uiudLrjoYwHu95JY+fkc2CUEX547HbrJK/IWspSn0XqrIpMhgFwsmLOB0v4Fu1ClQSr5N6Kp50BJARhO/etf1JqjQBFTCnELBg7r2ZSTbJmYNLWN/kcBOyut7qaGZd3NbM/1lvTf00ev13rlO+8xjacS4A58bIKg0u/Lg84JEwCTcEs=
    secretsCookie: AQAkjEKquEzP9lgzmnmiNOjEV7SNBUFx2imZ5DxpDvW1w7CYdvFTYhUiTv3gLKCzoNmSNIcuAMVTLNKlGmBlaxBN+yr0uLiQSxU4kyaPgtZUB8r2u/fDgjsCAZ8cKkUHkvXsF3Bu7OI70TaCZeXUx/LpCCcPCxxvZOBD7pN/DmZEI1WFxfdf2g6WlKIizNbNYAYpzRM2qTxLofW9mD0byNNa0scqrG8k1R07egM2lnzQCgn4bhiUyAeSvdzRmZfCloOGfjU6/1DqYVCEF3n/1Mzj9owAUsWczh3vwn6LiFgA2s/aKxxUomRXFXybBZuLA92nXugDNKoFyT2TTinZkfXlUeUEVHLBl6d9TUlTzXYJxPOU2DI3qT7Qm+kYnF6pJQjHGf8vGpFWcTNSa0yjK/BM
    secretsSystem: AQBe7iPNAed671uo/TTX4v8W74DwlnPeGuSur9eVTmf05zZ9DoVVshw3u1LRGEEhkL8TnU78Uq2T1Eft/fmTVlSUJzRNAxIK+C9MRieQH1NNL5IlvRdcBb43+rDkJUtIg0kvU9kM1z121Q7nydqWzvjiMXWDzQyisZ7/FkkTmUWsDHxH9P3KHEyoJWG7GY14WBmVB2W7z9o65TGAyRvcF2BiVrWdiQmmLAGfP0d8/+nZlmECsLuQCIKdkjKB0d5haiUa7VJiaffdStN+EyMfTLYqikIIemJ8kJREKVqXoqUHzpTgYhdwi7E74hlzhRihrTyfKW/l6spKmjDV15X1Ck5DRudiOeVUnShjrhrjOh6XSdEHJlO9DRdnC0lVIKkSHo81tkoIDdzCIDQnwiuJrjHv
  template:
    metadata:
      creationTimestamp: null
      name: hydra-secret
      namespace: ory
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: accounts-ui-secret
  namespace: ory
spec:
  encryptedData:
    secretsCSRFCookie: AQBZALkZLRSeHC9fhJAY0zFRcMSVWbTVBAmyhQvhcSaIwhv/GK6tSPIZPDLa2MsVY7PR1Nnf2ZMhIoTcGkj1EeqQQXBHxxoKno1NqndjEMI+ktQH1LTlp/AZv81dvtI+N820rp52F3ougytVpvthKO3jwWuRJL5Pg+qO1bHlpVMp2vl7MpfJVi9wSGz9rh6U5dEcB0cArsr905WbDeEB4gsvmkV3oJkIjl4coed+CfvO4YNsCndEPyfz0JMOUbRmDFVVotDJcCjFhLeAPjOaEgfHqNSDJVPm1IEu26UD+MT4t+9DNlSMvsVtKdulg3zpD04qwDcAZ3AFwe06axdjfRpZVOmjPbthMntU24FcqsU2mwBMKB3x0jBckdTuwcec7HQkY/4vGrW4s3hcucmKUG/G
    secretsCookie: AQBlqhLTPz6tgmNoqCJRe+CBrtMsZpIqRJWf3b/7T/599wuOTiwMFRXAUcgnEu8EdoWxWogxsui27lFbrmXphjIYwLh8y/zi5bqBfHs0PuXapwEo4ZsGh7C1Bo5NFrNdgtSwc+tnfahWCfc1hB+ImgEv/VrFZsfhC8D2R7v5AVfS0S/kvE3KTD4iXDdhM5sLTKULmvXlLUmj7KcRVt2zocdX5N3xvjw70NKaf7Ten03B5Zko/C6flhgpJoPJxGjTa/bG5LU1Eq2lAzs/POjE8D6Bj4dzwabfJjYQhV/i7/xDhwSDIQwMMUgsIa93MZoSb0OytbvcrTTqsnbxEYN+4nYtqSmVIfyN9kpPonRJrP8UgK6CorFFeHuNxCku2xpBnVNVKG032uFFe6+QFL+5Zsg+
  template:
    metadata:
      creationTimestamp: null
      name: accounts-ui-secret
      namespace: ory

