---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ory
spec:
  encryptedData:
    admin-password: AQBE4ZlaFBn/hZyu/N9M9I0B1tdMrgQjwrjtDXV1p6jCRJC4WPH2OpWk2lpYKQIT5RgpHbRjwiScsPLKF6SFNOKTN33hr8ZuSEcMSOVorHSjhx80B0usWq9+SFUPRFmXWOmV9SRd07MSEFB+L5T+lPMVTHa7OdsLnWNF3RUgP+MfPIB+Z+/qWxH2VHQUoFtwniRNw9vIQEAMoDxF3Eoh1PsGx4Vc6+pmbEEIbUQzCJuarZSeYsW2F07KLdRpEWwRDaPo0UlzA/wWghFy1vCr4QeA8LG4zr/ow97AAb7oybYa7XXN3d0zPa/Oo0yvWsgXKDoSpHgw9+dOxN9GHpC2hZlWDrpNo9ubhsgPIw/NbJAzIjN2ESiJjwxCL/8aRZ4FNPNhrLdgq/OwNjTMY851pWt8vLWXRg==
    password: AQAqBWjWMlANR9NJLzwr+V7cWyNaGRhdiwHAPjPi0jcYA4IBMpL0nLUx8NumH8zGzU51yoSDjoHQYIUj/Btl9RKWPqxzBX36rdP+h35/PupZzI5Td8mD3Z+t+cQJNJvc/9Jc7jdgO9a/WpVUQ9gmyAKvmH4XR7IDeqHaEVkjMVvqk01OW5t9TJHfAa4VMro9l6F4akyNFnIJejuRNRjPHiVKBW9BjmWWEioS7WXgKDArfGWefCuBmsRsv6JmTmdlOA4KUnqFjf0Y+3JlFdPYlmz+YnHQREzPSh6t+i8raO7fpUGQx+jlmEV4hiZ2GsI1Ikwpbv9W606VoaHIx61/mZQvozBmkNYF3GdYELiab7oVUFfMtyzhnRlVu29fbWFfbUgnfWibeyKZH64EEuga82gW1aAj9g==
    replication-password: AQARYzMaJP9on8+jARWq4fwKr8EP19dtKPiVngQR+p9jP+mAtDObx0n3n/ElsQHWEE8fjPoMn3xXdGhwNj3Kf5UNcY9uLCmJueGrm4qN8+q9+ml8u2h0XQ9HZ7H36eQIL1Zd08sfqIaLw1+OkhZnygSYBLlZwbe0BcOJiJ3WQOJbLiT6TOxwQfTQB5Rv8yHS8RhvPthbVBlBNLzWf6J+4p62YjlBKMJ8sDXqtMPowBPlUcAmBgjb1JUj/HG+oBBnfmcnihvEeLFjF2JfJDhYI35AGskD6DF3L0gSoPckFR3xOi/ZILavm7CpZbdmYHrqJKU7z5mbsZSJiEnyLqtLbb38IKHagDC5QYvDRNhSg+j0Z18GzZX0VlxDxkk2rCDbZqbegOnijgNdvU8brmP0tlLFb8eOKQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: ory
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kratos-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQBztt30aBgYRPDMXFIW7N8LKxp1yGcuIztVqzKTC9csT874akBPJEVvLmqkPPa1kvb8K7Vmb9gcjZJX72YFHxtLUHgMp1HbcJvkxCm/YvfaIq2U6jh5QxgoVd34z0z3kChgWuTYXndkORrNUGTiJ+qS8xmaj0L+7/Kpr8a/G7oU6OkD4IdWRNIPJmm7yc2Ryk+2J0wMjkMr28y9evsuyumbIdmzjO1Fi59aP0wydF1/hb0v0jN8NKwPh32DrxWqYvZVf4yrjkjPRVNbdCQdf3FBTLZ0h3n2YsJ2vPEFgbQY8LmMSYULEZqhM/UI5JOdXrWVO5oFKj8s3bi+9Bl4sXJuCn+cZtXEU43AIHvnW+jfvhldIGhGFYlideQcbvMBlaKOm9Dg5FUQjkEWXKtMkVh4ImstfmPGBQ82KEOSx4abubqPfUULH2rDLg15clgvs1BQ74SpzgbpbZENxvCB2hxGmnHpv6YDV8UbXRY=
    secretsCipher: AQAutK81Tcifq0HhpkyXa8GzsMtboqPoz351z5L9YVLFW1si4feYc93tu4piXo/ntgPm2Tw402eOcjdY/px/MPMLjgVhLYHZwH8UZmCEt40tzyx+AugYDJSy9ZiH2pccTx0fZdqgK0knnpcpENzEPeI1JSd+ydYfzX8WUFsaGSGB8W+q8kDwZYirhDpKsXGALHYMb64RD/AIie+KmuhNAylk4vcgEHCzknRk9cyB5zM534qa1gRvETPZn87Z8+4VOvyKkW86UwphbraV06faQnrDJtv6C3qRO19sb3morApnE5FCod2v6fM5LnvU6jlb+blt2mhfIbTYagyRkbFmcSraazxL1M/4Y/d8DCGyy7ykPuUwd1wvKkAoEXm0O6p0WMd5qRMF/QE5dPT8nPj9BYaV
    secretsCookie: AQBXsS2W0VlgN1xOfDMFjXI1mcW5AlIKN+0NvPLD05xZNR+81ktWCNDkCnS/icVTjmirzIvZQhOnqdvJ3XT6ZLmN16XNOF4mA0b1J8gpEq3klIjFpWmfkxNmDpCkt2bfhYWVkEagSwwgZbVDrk7yaMq8rH1SFcB16ReIf90TyfDOSOoP1L9ZskMwzKcmbNP0soNfqDV0E5Eii1BP1I0qjQzh2gOsBhdW1JpP5k2nuWClk+hb8cR3B1MYzP8iHYbm/4HxLM9A/ffg0bsj1NEHno1veBuI0DBJZLb73ONrT/hcRiMgU6WyETSwupHqMYYPqPTpjHE+PuKZ6qHOeOZK4kYuUQtjS000dd5ErdP5jl9yMYqfj2NTi+7tn97CGI74cKNy75Q81tPkXjJkr9mYOyw0
    secretsDefault: AQCea2zuCLdsXCKrVME4OQULFLK5yZ5PVtEvnDQ6FNI0m39iVSAs0e2nEmND0h9jbXe+tPOn1HXPuJW21dJ52ufGiofqbXaKcpoJscTHq/FXobBqycWJGU3zBENMuBg2x6VHqQv1FjSNL53YSZKvOdjnPA/hbnUTFCTEKP2M2Dh6uWxEz+AcdmdVWb00ve4s4PIaYAxzjQZkkONzRlPQVD9j6Uf9P8hjcG82e96hjNGcvdO450qK/wFyMNUgLo3xBxC7s9MSDjGWZkXRMoYta9KmCDQVYFJlaww3PoKaraVv7GI32RLUZIu39zejzSxrMxw3mJW6Gf+bQUU3Qk6hJDfQPef25PlpIwYaR4FfuuXDKTJ0RXFJvLhVwJv2nSoM5A75vWrBfr+nRwMcamRL/Ep+
    smtpConnectionURI: AQCIYhSDuaTb+ZRCeZasPUHiWobh4JFjfnlhnfvsIYZjXXVGDfv8U1BLD1nQZgFaS2+AdWw3tD7c8mYuITJgXnL8N7ed5aMxMgdBsuAzx3ZGfIrBT0+zc2N+fbHOzBmZw9If4nMRZ05RRMi3vrZg9xx+Ew+Kf8rBHEIpU0WygbWerjRPB9IjXsapt09Jp4gRcWZZ52dxQm0WypaXTm0PdW4t6iwLMa2lqInryWH/GZ31fghbnpWocyYmAYjq1gLS5wJf0Y/Qw/lSmmOE7snpWZ5yBIIjZZ+B/UpFBQA1eiQpQqdur0MJof4Rb5RXPmkivllzCQniv6X8bZE/OC2ECd+CStJ/lAcqj5ynmKMUxA+abkYkTfIWpfGzI49h6Eb3pFgPHeMJ/SDbd2Ftli1rB43JcjVFApGhildaalgpAlf3YQQUuUEhvSvtUw==
  template:
    metadata:
      creationTimestamp: null
      name: kratos-secret
      namespace: ory
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hydra-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQCHgqwDi2Nhp1z4t0+iRAwsPFlZDHZ08tje76jhSTgrGaUPlANqwK2BVE3nV0Vis/kvkrmVC3nsuJKNmPfSDj6vivyqhFOHxWxL15ep0WqdvhEsOYGW6Vd2QTz/FAPnFoef3KwECAyqwMjsJJgnr3NrEqXm5TbA85w6x5EFwYVaUqt1nQleFkW31G/KoFE7uixWRuGKi+BnXjjCdSd1RL+O1zAHbrLaiebbHrTWAUSMcKhbksRc3e7HlUDX1GAOn1W5qXJguIQ7363v+NHlXwjpGZWpnFynMNhQfmhbMflFlZrRbbyswnBGsqg6fJ2XZbsPp2KuPpzBlnJoDx/HvP4ZGTtVWxHAQHPYVyC9bQ/24PhaJ42yezO9d0uWEnMPtic3m4fR0Sxu6pSJh9eZlBp6XvZsh7RHEjTANascoR2GcWAw9T0QL73EAE4iE/nanFBEZczqCom6bo00S48AdawqSDZEohojZzg=
    secretsCookie: AQA/e97yZorfm9VjcYB+IgM3tRU+12fKJ/2hMeVivre6YKjFlbl+A/TxFAfbkAMABx7Pxy1Emmxy1OXhrRynH1dbR/LYt+4TRlry+M/1hxh/c6v73StEJimhjYTauNVk9nJ53D+FaNyay3F7HNajbxkogew8WCfY/Azh2qwb3BfDw+vfIEAwCOJe47IAUeql+Dvvx94jWwK6sjJ6EJMJV83O14DX+/d76jxJkqeJ/QpJ40lTPv25PRTPsuEJ5XV1cxqmi+L1cnEN85812dN4Tx4N0tcNRsaQkALxP9Tgg3thED8NUIpx2okBXkTZY5eszrpqYp5ggTrXIO5qICCeM4Nz9eEJHxOh3Dc8s132YuLbRvGEy6q1h3BJIFSL8Hnke7E4dYWAFCyVMAuud3z5nSAj
    secretsSystem: AQBTgM/LSMYgkZPhdND1ShkSoiva8szRkbXlw6TEnI3ThExxFMBlw/vKu/13cYlkwwmfDnht8WO1EyTtViIp4j+0Zjr4nnuqezkjwQTn/fq3+tRXnYfPc6spRaCai2++v8uqlGOStpnpvY8OBBX+fCSsu8oNCSefxYdCyXuh6HKQAAjANAIkIQ7G7ujoLCO4RvITovZ15qLcsQgSoKf3C2A1MHBWM44Rft1Isd0Vi9HlO3UWAd5nQrYjauwVRNdBoi4hR9PveWxpAjBJoHJj9YDhtUhPTpFdt5HhAv6ifDSbau5cXUNxrS4YNy6T7rTyMicQgGYSxIN3AuX5i0bSiHUjNA9wN5oWQ4wOQ0Utp+vRbOcZdhG8Q7fQvXp5dPyWkQVZDtkndDR5hJ4DV1l3OsA2
  template:
    metadata:
      creationTimestamp: null
      name: hydra-secret
      namespace: ory
