---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ory
spec:
  encryptedData:
    admin-password: AQChOOwokbrRPBZHC3WWKCISnTQKd9CS3y8aoBOHCM0pb0WKtLWUoo0D/f7UImUmPCJ3zyIVAw/CIQYqdhhp6JFxJT0ckO6nxGkx+mH3S/1nAeDXOP67OqsMNeVeaQCT+sCyyRQwJz/W0e25Xa9lefE+4L7yCp/KNO0qgETN7b/9A/vZ1izEKS8uVNuflJIwRByj66fqklm4ITHpaypCcXe3t3KqWyoSyHpqBI2pzizOEctjadd3Eqvdb5WDUt9CpHfRp0V9J0iuIkxDIfApSnhPmUV/xMahRO33HaAsM8Lcypex/TKQt/C8hXjWKJ8uJncnM7oS9miND3sRidc1HkB/T8gDrHOSdbqJbQrCArglgSQqWpmix+CCqLucIGkO3WXKHolFF4xAt8SzjdGvTuVZ
    password: AQB4bqvQKR6yfIL95HX0LAuI5XN8/YQDmVIIlRsxIblTjG8ffRV5XJQr8FbRR0pyJ4WU8w1pHZQo0iOnW+6CwxxMQgsOHsV9SytP7rHfiBxLHsqYFWxe7dQGKwnhDtPSUVNg8x9tn8C9WIx6xFN5oqLvdV4cfKgw3zf3HfSvAfJTbuLIqiPb6nFmtWWlI5i1Gj2Kax3tRduLJAIYtcjXczjU8tGSQ15touNVezlmIu1/XYUgqu1GgoE6YI8ER5Xb7MnbZG0FpFcJVSYD3lzRoySyTrVsEvce6qR3ehyNQFWEq51qYqivBTpyMhqpLtqOOaRehastntzYxK2GgAUYylwalRmeXyjI0MtrkcLgXLawMeLp64vyu/9Vx98qekUY7ymM724OXxE4li/oQlfWIfGq
    replication-password: AQB3zY0mXlYIBCtt5ao7KnNYt2DjvOIfPV4j//96OljKN+lrW8WXhEzwiAIgzjaHJ/2LtRNEZJn7BkvB1W/95GF7HPPN9+ZcmGRwH0XWFzWsXYKuhqeccpBIaL3OX6BiNRiioJLA6XWc1Z+IP8lf2eX8rw+GpSTngMwsLe3gXAlpz2sN42OzeHpPCa1ZDmjp32Wnob9DgqUmmHYIU1ffw1uvYo0XMDc5qE6Xb5ZQlT7nI3kNVHUDepe7mihIrOPmIAAgCt3ijkuOF0Ye7HaKoSS/b+OR6A6/vwL+1nLiaYeQAv1krEt7lavJshreObzLH+a0CMVDGw1zEX5n9t5c5BN1Vq0CLY8m6OYdBk1o9WuXBvqHIeFEilrV8ExTjaXhNfgZZ0xd/WlmW3kBkDRUwlK8
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql-secret
      namespace: ory
