---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ory
spec:
  encryptedData:
    admin-password: AQBE4ZlaFBn/hZyu/N9M9I0B1tdMrgQjwrjtDXV1p6jCRJC4WPH2OpWk2lpYKQIT5RgpHbRjwiScsPLKF6SFNOKTN33hr8ZuSEcMSOVorHSjhx80B0usWq9+SFUPRFmXWOmV9SRd07MSEFB+L5T+lPMVTHa7OdsLnWNF3RUgP+MfPIB+Z+/qWxH2VHQUoFtwniRNw9vIQEAMoDxF3Eoh1PsGx4Vc6+pmbEEIbUQzCJuarZSeYsW2F07KLdRpEWwRDaPo0UlzA/wWghFy1vCr4QeA8LG4zr/ow97AAb7oybYa7XXN3d0zPa/Oo0yvWsgXKDoSpHgw9+dOxN9GHpC2hZlWDrpNo9ubhsgPIw/NbJAzIjN2ESiJjwxCL/8aRZ4FNPNhrLdgq/OwNjTMY851pWt8vLWXRg==
    password: AQAqBWjWMlANR9NJLzwr+V7cWyNaGRhdiwHAPjPi0jcYA4IBMpL0nLUx8NumH8zGzU51yoSDjoHQYIUj/Btl9RKWPqxzBX36rdP+h35/PupZzI5Td8mD3Z+t+cQJNJvc/9Jc7jdgO9a/WpVUQ9gmyAKvmH4XR7IDeqHaEVkjMVvqk01OW5t9TJHfAa4VMro9l6F4akyNFnIJejuRNRjPHiVKBW9BjmWWEioS7WXgKDArfGWefCuBmsRsv6JmTmdlOA4KUnqFjf0Y+3JlFdPYlmz+YnHQREzPSh6t+i8raO7fpUGQx+jlmEV4hiZ2GsI1Ikwpbv9W606VoaHIx61/mZQvozBmkNYF3GdYELiab7oVUFfMtyzhnRlVu29fbWFfbUgnfWibeyKZH64EEuga82gW1aAj9g==
    replication-password: AQARYzMaJP9on8+jARWq4fwKr8EP19dtKPiVngQR+p9jP+mAtDObx0n3n/ElsQHWEE8fjPoMn3xXdGhwNj3Kf5UNcY9uLCmJueGrm4qN8+q9+ml8u2h0XQ9HZ7H36eQIL1Zd08sfqIaLw1+OkhZnygSYBLlZwbe0BcOJiJ3WQOJbLiT6TOxwQfTQB5Rv8yHS8RhvPthbVBlBNLzWf6J+4p62YjlBKMJ8sDXqtMPowBPlUcAmBgjb1JUj/HG+oBBnfmcnihvEeLFjF2JfJDhYI35AGskD6DF3L0gSoPckFR3xOi/ZILavm7CpZbdmYHrqJKU7z5mbsZSJiEnyLqtLbb38IKHagDC5QYvDRNhSg+j0Z18GzZX0VlxDxkk2rCDbZqbegOnijgNdvU8brmP0tlLFb8eOKQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: ory
