---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ory
spec:
  encryptedData:
    admin-password: AQBE4ZlaFBn/hZyu/N9M9I0B1tdMrgQjwrjtDXV1p6jCRJC4WPH2OpWk2lpYKQIT5RgpHbRjwiScsPLKF6SFNOKTN33hr8ZuSEcMSOVorHSjhx80B0usWq9+SFUPRFmXWOmV9SRd07MSEFB+L5T+lPMVTHa7OdsLnWNF3RUgP+MfPIB+Z+/qWxH2VHQUoFtwniRNw9vIQEAMoDxF3Eoh1PsGx4Vc6+pmbEEIbUQzCJuarZSeYsW2F07KLdRpEWwRDaPo0UlzA/wWghFy1vCr4QeA8LG4zr/ow97AAb7oybYa7XXN3d0zPa/Oo0yvWsgXKDoSpHgw9+dOxN9GHpC2hZlWDrpNo9ubhsgPIw/NbJAzIjN2ESiJjwxCL/8aRZ4FNPNhrLdgq/OwNjTMY851pWt8vLWXRg==
    password: AQAqBWjWMlANR9NJLzwr+V7cWyNaGRhdiwHAPjPi0jcYA4IBMpL0nLUx8NumH8zGzU51yoSDjoHQYIUj/Btl9RKWPqxzBX36rdP+h35/PupZzI5Td8mD3Z+t+cQJNJvc/9Jc7jdgO9a/WpVUQ9gmyAKvmH4XR7IDeqHaEVkjMVvqk01OW5t9TJHfAa4VMro9l6F4akyNFnIJejuRNRjPHiVKBW9BjmWWEioS7WXgKDArfGWefCuBmsRsv6JmTmdlOA4KUnqFjf0Y+3JlFdPYlmz+YnHQREzPSh6t+i8raO7fpUGQx+jlmEV4hiZ2GsI1Ikwpbv9W606VoaHIx61/mZQvozBmkNYF3GdYELiab7oVUFfMtyzhnRlVu29fbWFfbUgnfWibeyKZH64EEuga82gW1aAj9g==
    replication-password: AQARYzMaJP9on8+jARWq4fwKr8EP19dtKPiVngQR+p9jP+mAtDObx0n3n/ElsQHWEE8fjPoMn3xXdGhwNj3Kf5UNcY9uLCmJueGrm4qN8+q9+ml8u2h0XQ9HZ7H36eQIL1Zd08sfqIaLw1+OkhZnygSYBLlZwbe0BcOJiJ3WQOJbLiT6TOxwQfTQB5Rv8yHS8RhvPthbVBlBNLzWf6J+4p62YjlBKMJ8sDXqtMPowBPlUcAmBgjb1JUj/HG+oBBnfmcnihvEeLFjF2JfJDhYI35AGskD6DF3L0gSoPckFR3xOi/ZILavm7CpZbdmYHrqJKU7z5mbsZSJiEnyLqtLbb38IKHagDC5QYvDRNhSg+j0Z18GzZX0VlxDxkk2rCDbZqbegOnijgNdvU8brmP0tlLFb8eOKQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: ory
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kratos-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQB2XBn3i7tftb2mHfXyKN3gg6PghHeZpLbEiXf9+uU99fYh0pTwVCPy88n3ePZd9O1jwP/oA0uW/6boVwyWTG3uOvONTmgVPbNZxKlnx6VosLYwUUSJQAFxaXxnycOkYiXjBn5988Coh58MFboU/h23sMnM8bInqA2RXPaBZv2a19xHgfMQPMoOnOKVgMqMdM5xBfQZCtjh/YE0sPIGHjPE/kYhNFmrpXJrZulESwhSRrs1QY7cYhnIX07SIajcf9HVIKFw5jwUrojPr4ad1qsKVu4J8EmH5REhMYIRYYIF7TUWC4Zn9nR16WR4reRP7AFjFWajEjsRxcydOeFhY97w2grO90oveqxaNVGd1sUfktXQVz+UMJkO4bl331FxiKYsxzaF+0iUehiM/hnVDItG2QOimEVleGBQxjv7uLKAP8o5n8nSHeYdVn3Ayi4SYmPDO4JgAKZLSX2liYCGW8KZCrqw6plA4Si15BuDpeJY6Q==
    secretsCipher: AQAeXtOjgunXIKaRRQjPcK+7QVuCKVKuHhBV/cu31cV8uPxjPIebD+J8FAxsHQN0SG2oIFjp5nGy4VJOEPYMekqFI/HlOuo3cx6OOyM5Vxkc9dgSTTqMsHJ47s/PCoVa5vX0554B8ZrB4jxs2BhxARUEENvYFsJqxSMFrOMPcvMqnVC//LrjUIUntC96yG4TjqZgTf3S/lAPcBnpMYCKU2gCzVmxkLgDyQjO3YlwUY42z22+g2pCUdcJ5HaJhf2uGfDW8JNXox+yQ8sJfmcMEjlAU+ZlZYx7N4i5MfUCLhMaXd0YTRdIL7YftfZMnje9EgdQKePnanMdn6+f4Vf+UA+QjvdBWzVK8Bb8AvQOb0pmVQW6W119AJfoVem6vNEHkXVXY3zPOf+kvLc6wWo1p2pn2/vq6LO00kodylIweJdmDuwN
    secretsCookie: AQA3act89zBxRJovGVCUZyg8LmkVNUUkcnf3NYoejT0IHQLhEJZDRdFQuJKl0TlZ/ebwUmnq5E6k9gClHCu++7bKOpfk+00V4mekbMKdMfSOC3jQjYxQvT7JXOnKiI5IC8yNpsKdg9ClX79bN89xycg8zWgDBKgZXfkfEhaWFvax5vhLBP9L7EiZ1u50q+WjJHmW2UC0GqMA/X4qQyXIMYWIBImrjHgWb7SwJdhCPHrFD7ysL+Z3Hh5muaewZIaF9jO2ZN+ThprcyiZgydyQqblVCN53UXbjjNoZmvaL1E5IM52RYIhtj1XyRNglBcgWV56s7y3l3wjJI2W4KQsx/9dDxyKmIitvjkvzpVK6WWJ4qivF6090EqmyyLRx/EjN+6DRqIsqD91XKGTLEgfAbKrgUtpwI1LR5JifpNPOKMpS0ke5
    secretsDefault: AQAyMBbXR+D2Rh80mZzvbb/VPwsU4JOdZ6iVi8SDRtRlnmRJuGnhEghmN/T+/NIEcUopLXhIw0/3w1SM6KteY6tUGvjzSmJATdP5+fXiEeQbTrsonYQkiI+b0e8DPjOw8cNXueLly4RKvBTgo0Du6JFsqgt15c1qgzfUh+54/bz3HNmaYBCtw9pDQtbMst8FdFyF6RQlcl/s4vnmSBGyZOAydQf+rVHaQa4aUolrt7WAeCZk/t01bc/8HmOVX7dExF/pYa4rBHSRaXjNkhWl6xRRA4lokzF+LIeEoDrF9+lZHp3Q+1jhKHLaDkDK28ncxwSuK/rWPdtF2EIvOfCVIPvK5tn9QhRHgdObjb8AZAnNreaRGVHYsx35XIiINXD64khOK2TP4VV729+b13Oz43lon5H05R1F8GoWhk0M7/T7+GDV
    smtpConnectionURI: AQAU8Ch34++tRHxoHmItxkQwJQ07131Gy3qLifkVe+5nNt8C7pSfmuBeMGzdFV3cm6MEaqq6NM5lGBeirENai1VsgW4bRxfeDnkrLzUsCoN0EvmAIqhcvI163SVTLWZWJPXlp/ENvJv94ZYf/hG9TiijT8yu50Apyypp8i1uxT1UPSo8TV4Z97Onsf1DWdVwROZi7R3dZZu5psbYV4AJC/dRB5jGNe+amVY1vDj+GVL18TVhrcSB/NDfDm1mjkwyycNDF82wNfhwImu/fl8pF/R7iS/e6vb1qZy87HXeHlvrp1YPL5kvWETjC+fcGb1WVzrUuWzczFwEkYy5ReQdZMsV++YrFCRKRJMFq1/plaw1JR1X0TC/n1flP6jaBONqStIkkK1SYfoRkgUmS37xK7AZ/UzbSRG10yJyXi85yl5rU3jviLLp/kg2ug==
  template:
    metadata:
      creationTimestamp: null
      name: kratos-secret
      namespace: ory
