---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ory
spec:
  encryptedData:
    admin-password: AQBE4ZlaFBn/hZyu/N9M9I0B1tdMrgQjwrjtDXV1p6jCRJC4WPH2OpWk2lpYKQIT5RgpHbRjwiScsPLKF6SFNOKTN33hr8ZuSEcMSOVorHSjhx80B0usWq9+SFUPRFmXWOmV9SRd07MSEFB+L5T+lPMVTHa7OdsLnWNF3RUgP+MfPIB+Z+/qWxH2VHQUoFtwniRNw9vIQEAMoDxF3Eoh1PsGx4Vc6+pmbEEIbUQzCJuarZSeYsW2F07KLdRpEWwRDaPo0UlzA/wWghFy1vCr4QeA8LG4zr/ow97AAb7oybYa7XXN3d0zPa/Oo0yvWsgXKDoSpHgw9+dOxN9GHpC2hZlWDrpNo9ubhsgPIw/NbJAzIjN2ESiJjwxCL/8aRZ4FNPNhrLdgq/OwNjTMY851pWt8vLWXRg==
    password: AQAqBWjWMlANR9NJLzwr+V7cWyNaGRhdiwHAPjPi0jcYA4IBMpL0nLUx8NumH8zGzU51yoSDjoHQYIUj/Btl9RKWPqxzBX36rdP+h35/PupZzI5Td8mD3Z+t+cQJNJvc/9Jc7jdgO9a/WpVUQ9gmyAKvmH4XR7IDeqHaEVkjMVvqk01OW5t9TJHfAa4VMro9l6F4akyNFnIJejuRNRjPHiVKBW9BjmWWEioS7WXgKDArfGWefCuBmsRsv6JmTmdlOA4KUnqFjf0Y+3JlFdPYlmz+YnHQREzPSh6t+i8raO7fpUGQx+jlmEV4hiZ2GsI1Ikwpbv9W606VoaHIx61/mZQvozBmkNYF3GdYELiab7oVUFfMtyzhnRlVu29fbWFfbUgnfWibeyKZH64EEuga82gW1aAj9g==
    replication-password: AQARYzMaJP9on8+jARWq4fwKr8EP19dtKPiVngQR+p9jP+mAtDObx0n3n/ElsQHWEE8fjPoMn3xXdGhwNj3Kf5UNcY9uLCmJueGrm4qN8+q9+ml8u2h0XQ9HZ7H36eQIL1Zd08sfqIaLw1+OkhZnygSYBLlZwbe0BcOJiJ3WQOJbLiT6TOxwQfTQB5Rv8yHS8RhvPthbVBlBNLzWf6J+4p62YjlBKMJ8sDXqtMPowBPlUcAmBgjb1JUj/HG+oBBnfmcnihvEeLFjF2JfJDhYI35AGskD6DF3L0gSoPckFR3xOi/ZILavm7CpZbdmYHrqJKU7z5mbsZSJiEnyLqtLbb38IKHagDC5QYvDRNhSg+j0Z18GzZX0VlxDxkk2rCDbZqbegOnijgNdvU8brmP0tlLFb8eOKQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: ory
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kratos-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQASeAk+sxVMzSN9XQweZz0TsP+Wr/CbEfSMTZpR4SR2XDNzhMwgN/zTj17LTtspVt3HHWasGjAEKVCtSCYH3rVUbB5JDRwtXZExcLBzuSRmv6LWGriYmkfvfF58dwaMFCXCKb0VRYBJOaJutzewmHfPdMxptkPuC2qfB2kvbpObYn8KyGfNJWBB+ZyqWMhzs/s/CH/CXK6mRfJ20iOnL5E8RJ8AtmYP3Blo/X/1Z3inEGkGRsnSwxBWBKudTchEr4xmofh/FF3GYWG6m5YGm3P5OZbnhKZ538sJ+nNcGFR1zRTc2Vmi/EiXA3zF0bP4GVsEg+byAEGRf2lVs6FrcFMUkC2uzbIKA9qsdpdt+NQtoIYwetOks6Nk8EkXJqS691MHQmDJzBC9R7AEufX2O87sZuTJHV3aHrR5Dak3NE6xl45RGAJ/omihb/mb8xzM23XSgHOwJzrf7/iQjiAuGiaIndOK9dSxhTrELyO+tIaP2w==
    secretsCipher: AQA/KA2pwRykzDEw06OkfNzd37z5iq2ar+ZRgI03I+oIQQow0lVZ5pExNPDqwZ6CyjdYHfJffBselVr4T9+8+c5sPrv9AtAKKD4lElebyaCLlVBrcEwwSk0H8xS9pKkJU11wGPOYu5HF0hBgCMWVW5Auxsc0yz0ozRGLGsRnkMCshkfnzKmSCUCKNAkHcJuUJ32AfytaXiOgOZm59sDAPzeNkV9T2wI7xvNNwx+Az1EmDMwxbL1S+fgz0rfHmLiABcflh1PcebhONWrhmT+ANPqr8fUKSKNB6v9SfOw7zQBFaOqKjVPvwjxYhqiaaVmy8hUjthNa0hbAbyYK6GRu6Soy6PB6w8Dk+tkD6paGWpf4auiwnpkLEod1NMVMkskdPdq0tHo+QjkNTr3PnCwUKQwY
    secretsCookie: AQA+hNOnq+/h0HYTeXAoBzxX2v0Me9AgW4gXchONOhrDGFdnV5PCuIQVSpcOG1J0dpwsU2GcKKLW+PZ9i5s1BALyG74IsLDKutmgdUBbx3e16Kn0MhNSTaA6YhpFsT9gJP5DQB5IP3q4Zo2sW4WTwDAW5yf+LHD2SbIONGTgRRdV1WCJ9ooIvOO2dY447Xg//KppWWOLesxtapj2ZUHXcLLz1vFnOXXiZ9UmNpPYKgFoY+CGYQEXCvdtHmUZ7wSOWd5BN1CJdXkPtowIHJ3jztcBfyj7+UBWDcDA/Z/C2gQ0k6asoEeiNhVYWIw7020v20FkmfV/MhgomOS6qTfCeeMiHIjFYtzVsI7GIUUl9UgzxfI7EdkQrXPb/rYMn8nXw9Fow5r9acIBRjYJoeOU2wng
    secretsDefault: AQApeIk8SUPpEkDq5ZGdAbeJt5K1HduPV9UyuIfEVcNm8kpAXL3mmj1KN3V3/+aiMGllqzwEWiUYjRLySEZTTS/T4bxXqvgqGU3DKlXAfus5gVFvJ0n7/tRiK9fdkZrzjLDjNiZLjznjb7DaCUYD4JryBCbribtG1c7Jphn36uNBpoGRPxHMdNFJe3Z1VtYg/b71Bt94YPzd5Wp1/T5GE0IjYO1sBmyjs8A3IbDP3KKoGy8Q77kD20jjDV/4g4uNnrO2L9hdSginyeRHTvbMNd+6tdVBVx7GD4Ksta4wRGGolO1fS6C2fq4dFwHG69IYQdJxYwjD173BSI85N1V3/BhLziOGjoxCyP8mn9qYq62RrX7Zy+PVhOxsr0ILvpht/U2l+qolw87otgv65f17rZte
    smtpConnectionURI: AQARnCXa8BvevBFd9ldH7tbQYd+DaYhHClJBzo/aq5ulxpD8nCPI90TXqOeZ10c9Ozb3UNbxddB2Jkrz/2WutJWjlzKDPn4FSVdnO57Y1ru9pfXPhsbuDqyQeRgBR0JRDDV9gh+ATMyL0KSdIxCneLOItwfAFSrc2FEH0D8Lio24WGX5LXgP6tgSMhoEStJUW/MAd4WM6+Vo+9vkiOnfivLhyvmobVmeWwZVvMaQI44MZcCNDU3w+OOi3MK8Aan/ixv634h/Lb4U+lF1dlaWCRPKl0RUNtidLAU87oPB2S+vKS15olHZOeJGNQhrlQl7TfsMwEXSLB719gqUtU4IfvvL8zI1aH2oxKHEhVJP04jRerPswY8AYK0krGoXh8VeC7lU5Qs6STPN1/ou96DfeX5o+hBdK3setu0ZCnRADNE6eFvkeZ8HngJWvw==
  template:
    metadata:
      creationTimestamp: null
      name: kratos-secret
      namespace: ory