---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ory
spec:
  encryptedData:
    admin-password: AQBE4ZlaFBn/hZyu/N9M9I0B1tdMrgQjwrjtDXV1p6jCRJC4WPH2OpWk2lpYKQIT5RgpHbRjwiScsPLKF6SFNOKTN33hr8ZuSEcMSOVorHSjhx80B0usWq9+SFUPRFmXWOmV9SRd07MSEFB+L5T+lPMVTHa7OdsLnWNF3RUgP+MfPIB+Z+/qWxH2VHQUoFtwniRNw9vIQEAMoDxF3Eoh1PsGx4Vc6+pmbEEIbUQzCJuarZSeYsW2F07KLdRpEWwRDaPo0UlzA/wWghFy1vCr4QeA8LG4zr/ow97AAb7oybYa7XXN3d0zPa/Oo0yvWsgXKDoSpHgw9+dOxN9GHpC2hZlWDrpNo9ubhsgPIw/NbJAzIjN2ESiJjwxCL/8aRZ4FNPNhrLdgq/OwNjTMY851pWt8vLWXRg==
    password: AQAqBWjWMlANR9NJLzwr+V7cWyNaGRhdiwHAPjPi0jcYA4IBMpL0nLUx8NumH8zGzU51yoSDjoHQYIUj/Btl9RKWPqxzBX36rdP+h35/PupZzI5Td8mD3Z+t+cQJNJvc/9Jc7jdgO9a/WpVUQ9gmyAKvmH4XR7IDeqHaEVkjMVvqk01OW5t9TJHfAa4VMro9l6F4akyNFnIJejuRNRjPHiVKBW9BjmWWEioS7WXgKDArfGWefCuBmsRsv6JmTmdlOA4KUnqFjf0Y+3JlFdPYlmz+YnHQREzPSh6t+i8raO7fpUGQx+jlmEV4hiZ2GsI1Ikwpbv9W606VoaHIx61/mZQvozBmkNYF3GdYELiab7oVUFfMtyzhnRlVu29fbWFfbUgnfWibeyKZH64EEuga82gW1aAj9g==
    replication-password: AQARYzMaJP9on8+jARWq4fwKr8EP19dtKPiVngQR+p9jP+mAtDObx0n3n/ElsQHWEE8fjPoMn3xXdGhwNj3Kf5UNcY9uLCmJueGrm4qN8+q9+ml8u2h0XQ9HZ7H36eQIL1Zd08sfqIaLw1+OkhZnygSYBLlZwbe0BcOJiJ3WQOJbLiT6TOxwQfTQB5Rv8yHS8RhvPthbVBlBNLzWf6J+4p62YjlBKMJ8sDXqtMPowBPlUcAmBgjb1JUj/HG+oBBnfmcnihvEeLFjF2JfJDhYI35AGskD6DF3L0gSoPckFR3xOi/ZILavm7CpZbdmYHrqJKU7z5mbsZSJiEnyLqtLbb38IKHagDC5QYvDRNhSg+j0Z18GzZX0VlxDxkk2rCDbZqbegOnijgNdvU8brmP0tlLFb8eOKQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: ory    
      annotations:
        helm.sh/hook: 'pre-install, pre-upgrade'
        helm.sh/hook-delete-policy: before-hook-creation
        helm.sh/hook-weight: '-1'

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kratos-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQBe5XnPFRPs2GdjLR9KcSZ3c2nCnm/cuuNh1LEjtyrpARlJkgO+WH5AwbvWvlIlQezkWjAJqyjuwSGrisFPTXpSEzAoeQbfWpPDDdhrBFq+FUWD7GWh4/0txdt0BW4Wm43I4zr6j7VHEYRG3s+rVwQzuyXEM2BU9VroWX4HGzQxntkBxOw6uCKlaEleedIDdzwDAHnjNuDFDmdZRCy3OW+Q52c5gQkfpiR8addUFPzy7CNOaubuXJvfmePxUuB2zH05BHeKO2U/bMD3j8UGZnjyeGdKN9romavQ/+1h8qpQZhv1avBWsGCEaKUdqskMrBHUCekpYrQCS2FKCeqiint1gSY7lA7CdUIlqxh4FMOdxdEn8lgsCDfaeR0gFSGkZSKley0WYLcmA1b+IT97w8mY9NeXHVZXGPy5Kf543InQFnjtfLZE4CFkwCPP0o3ogbTsU1YVLY9+2BLb54Z2DhyYbiPy0U/3Y/Fguj/2Mj4=
    github-client-secret: AQCjqpahxENRwPaKv93FnzN6I1NtziRnmZC+bUzjV8o7ZMTckz4nwbd0Ih7rw8vz4lZS7rveN6CgdWXd+lb0eQyjO2nK2+zGR18GiPjTe3fr0i/JjYfrkkF3b+u8fdfy1uipsu1ws2l5qWMQr8zS6dBi5lUa/vZImcZx6zNZZ7LzB2nWuWRac5QPye8eDJ6rYXXBGeElCZjlvkq3x+h7d+8YmHxmA5uaeycXKF7irT6Rw0TouUzio7VOQNPv+BFXAfAdrh7C6jTo1NSRdGU9mr3iKyKUrmbXI+ePIS89XyfSz8UGQ0V1GNgrbL9iSeNgtGA0YIt6tSWRZbe0yEc2wPLkrZPhm2lGgznR/s+RHxojb3Mvd7LSSW9M+1Ah7FfD8V9OTWlMiHzVj8nnN+m5Ivfw/gdUBUWM2PY=
    google-client-secret: AQB7BJMCsL0oq8rM6hsTNTxPpMaOZu/PATpYXNeTo+sFKmAOVVxMauQXPwZMBpyuXdfvUKe+7bTT68Av9jRmhvZvqa1dWW9Je+/Fhe6zu7yC6xL3bJ657L7kc8p+9hBRiItXFMsQB5+sS/DhYIoqbklQcqNWzZnPxHIoPS2xURytpChWlqbkC0SHxZ2iab2ar0eiCACvv9J6JaK/GT93fQNTqXZ1Q8CTDcKlev/SB7w15w3EPe9+hgpNhZR1Ajkqyolcs/SOcGVq8CmNr6dgmWKyEecvUyJMy8rUfPdoHI7vbeLTNvH6MEJaBYQD9EphwBg0BhCQJRAy8YBxmgSHfUqY25igM7EK2bJs0FByOXcfo/SzNJLDuud1uEUlMaC1OV6IMk9QVYzwfUFJXfUa6BgWIzCS
    secretsCipher: AQAbwS+kkSSZ3XVDdSI95NKJyjFnJ+2ywsgVhPAC3u705+fByanAbF4x9JgNuEUWlAjZKPEm+FRVY6lR0ry3R3FMVkrw1JJnS4KybrfJ8UCj8aN/R+BCHeqnlVmnxHYMNd/LL480gAS9QmoY6VvSogpdXepFVJRpUO2F3B4gNuLIfdsOjxafUxzfRjg1rULBQvhf4AHHoJAp3ex3VBUW2SWYUVDEzOQiM8CSfdXVfoau0+NyLNXe2jRD7bLKu0PDthc1bN8U8MmMRezakH8mYDheAecDwgQKz6Nt4b9DivBcnznDsyWHxt+edStrOyIzQ69NdDmx6M193weobLkafmYzxXi559z7ayZa6+uyUxFixX3pkLikM/lXCwFzdwAkjzfDB/wD3+rt8dyBFa93mpb2
    secretsCookie: AQBljhJwbNDw4kSpnOcBNtnMfGxPDZIXWIN8MFxVBCNgwsVfSetKfazsUmWnuSturyQBYC8yg+pKS0fNHErUTzwc44laAbL1/D3DTgK6tqn1tOI/7VfatR450RCqdUfmsTQtm+HvpYMyNzu9lonXPSe1A2IP9k5fG6jL9D3oD8ODLmrZphzTVT4Q++zAQ3esQZQLhw5QQUoY6ERKzvyOGJG+nCdyH2NnT8AD1EF3PJPylgZ22ZcptWlDoCjQoLs8Xyc4lpDg8hnGRDhLdj9YZShclk8Dw31BbF+bLnOMvnAQInmgKAYmy/QcGBlHWXYF8Sgu9I4o56oCJjVw5DcXUXRL+i8+uCdOqGW8CHfv5soYTVW7nLNnTjvcYNFvRO8nYaMi3rHXNvP/qupQfUl219Wd
    secretsDefault: AQAAXAlyOCRNcVE+GG5XMIhzEXje0D0zB5d7CMlFVpkNpHA5NTHEDT2c7xwN/NTlmV+3h/U+Fs+uKz1MENUwCJ64yF6/33bl0amEOPAHPLxnFvC3nVhh+1iLpJxTXDsYtYxhGyfO3Shr9d0LCrUcJMaa5niJSsWQAraNZcMhIlX1Z3/VDawzbB6PFGcTATEhTnM4A/w6wzbHPwXcjL9oUgoivU0j1B2F8XpJ4tFFGo5Jm7xaUANyNj3w1Pun4iXrI/Lj36Yz8rMEJtYUJd47Aq7I+zQX+mHFMw9gdJ3NFTiAX4EEvANF4nmALG6TiH9S/9JyOgdi/6VHpNWq+c0Ra91J9orb5rG4S3HOaVoUA4p4xNAHdFEtDUDWX7Y+bfhKp2g+vJ035KKQu8Z5cJxR3KDM
    smtpConnectionURI: AQBCIMwOJ5nwe84hy/nZ8B+cHubB14m2d9rPaiIjMHjUuyuKl/kibF6ABVxrPE5rjp8t3u9f5zGghuYEe4IAF+Hp+p2UP3oTRVzRbQrm6GNDGrVKe7bipriyYz1AhKBp8pTKU0AZMr0PQ+2bF41lR2mbG4IBbmeZEy+K5JnZiKBb3vyT7rkHgto023GnQTezWTJrkMo01pTwE/7Ya5JyFpafGUuXDWjORtkSRAIle267wE1ll/Y6iRgsvAGSWkZLfIOu/vQgJ+httLcf75AXf9NHMb1INELaRTqrA6A6m2ntpYIqDXp1xqvpc/m5FHciLRBv2XjxthGBjmJSTJLkAK9PwW2gDzi4PsOuAgNK7Iy39GWRIKmV4IjiSl5tlPHM+y4rSQDQ5n5cFSMMaRECmBgwoFoEsrPYlp+wv6JTQGO0WxSY7MGiOrubKA==
  template:
    metadata:
      creationTimestamp: null
      name: kratos-secret
      namespace: ory 
      annotations:
        helm.sh/hook: 'pre-install, pre-upgrade'
        helm.sh/hook-delete-policy: before-hook-creation
        helm.sh/hook-weight: '-1'

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hydra-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQB9ZU65qjfE/gOSZaly5uV1MQ1UKBa4iCVSh5Huno4LZspQQaUsM+FGhmg+n2UECQAgrG314KwqOy+31Fq76DVsQkYTIcnpjq/vQKvtU8GxXEbdgdx0XS3ndb0TWzYik+mLK1W/bdy+ep1FAZxWv6b6+xdAtJMwEqJIe4fJQZlVuGotBH69SgA+DwOxlgcHWClu2RbpA3Af8HVrOJP9PkQ5SCTJGNhix+dRJ3UvcRWlp5aGJrxsrPI+QaONLZj+VW3vylB+6GnWzVFTcfJxbeQznztVCb2G+YlxMlJOkANc46n4jOZi22J7uiudLrjoYwHu95JY+fkc2CUEX547HbrJK/IWspSn0XqrIpMhgFwsmLOB0v4Fu1ClQSr5N6Kp50BJARhO/etf1JqjQBFTCnELBg7r2ZSTbJmYNLWN/kcBOyut7qaGZd3NbM/1lvTf00ev13rlO+8xjacS4A58bIKg0u/Lg84JEwCTcEs=
    secretsCookie: AQAkjEKquEzP9lgzmnmiNOjEV7SNBUFx2imZ5DxpDvW1w7CYdvFTYhUiTv3gLKCzoNmSNIcuAMVTLNKlGmBlaxBN+yr0uLiQSxU4kyaPgtZUB8r2u/fDgjsCAZ8cKkUHkvXsF3Bu7OI70TaCZeXUx/LpCCcPCxxvZOBD7pN/DmZEI1WFxfdf2g6WlKIizNbNYAYpzRM2qTxLofW9mD0byNNa0scqrG8k1R07egM2lnzQCgn4bhiUyAeSvdzRmZfCloOGfjU6/1DqYVCEF3n/1Mzj9owAUsWczh3vwn6LiFgA2s/aKxxUomRXFXybBZuLA92nXugDNKoFyT2TTinZkfXlUeUEVHLBl6d9TUlTzXYJxPOU2DI3qT7Qm+kYnF6pJQjHGf8vGpFWcTNSa0yjK/BM
    secretsSystem: AQBe7iPNAed671uo/TTX4v8W74DwlnPeGuSur9eVTmf05zZ9DoVVshw3u1LRGEEhkL8TnU78Uq2T1Eft/fmTVlSUJzRNAxIK+C9MRieQH1NNL5IlvRdcBb43+rDkJUtIg0kvU9kM1z121Q7nydqWzvjiMXWDzQyisZ7/FkkTmUWsDHxH9P3KHEyoJWG7GY14WBmVB2W7z9o65TGAyRvcF2BiVrWdiQmmLAGfP0d8/+nZlmECsLuQCIKdkjKB0d5haiUa7VJiaffdStN+EyMfTLYqikIIemJ8kJREKVqXoqUHzpTgYhdwi7E74hlzhRihrTyfKW/l6spKmjDV15X1Ck5DRudiOeVUnShjrhrjOh6XSdEHJlO9DRdnC0lVIKkSHo81tkoIDdzCIDQnwiuJrjHv
  template:
    metadata:
      creationTimestamp: null
      name: hydra-secret
      namespace: ory    
      annotations:
        helm.sh/hook: 'pre-install, pre-upgrade'
        helm.sh/hook-delete-policy: before-hook-creation
        helm.sh/hook-weight: '-1'
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: accounts-ui-secret
  namespace: ory
spec:
  encryptedData:
    secretsCSRFCookie: AQBZALkZLRSeHC9fhJAY0zFRcMSVWbTVBAmyhQvhcSaIwhv/GK6tSPIZPDLa2MsVY7PR1Nnf2ZMhIoTcGkj1EeqQQXBHxxoKno1NqndjEMI+ktQH1LTlp/AZv81dvtI+N820rp52F3ougytVpvthKO3jwWuRJL5Pg+qO1bHlpVMp2vl7MpfJVi9wSGz9rh6U5dEcB0cArsr905WbDeEB4gsvmkV3oJkIjl4coed+CfvO4YNsCndEPyfz0JMOUbRmDFVVotDJcCjFhLeAPjOaEgfHqNSDJVPm1IEu26UD+MT4t+9DNlSMvsVtKdulg3zpD04qwDcAZ3AFwe06axdjfRpZVOmjPbthMntU24FcqsU2mwBMKB3x0jBckdTuwcec7HQkY/4vGrW4s3hcucmKUG/G
    secretsCookie: AQBlqhLTPz6tgmNoqCJRe+CBrtMsZpIqRJWf3b/7T/599wuOTiwMFRXAUcgnEu8EdoWxWogxsui27lFbrmXphjIYwLh8y/zi5bqBfHs0PuXapwEo4ZsGh7C1Bo5NFrNdgtSwc+tnfahWCfc1hB+ImgEv/VrFZsfhC8D2R7v5AVfS0S/kvE3KTD4iXDdhM5sLTKULmvXlLUmj7KcRVt2zocdX5N3xvjw70NKaf7Ten03B5Zko/C6flhgpJoPJxGjTa/bG5LU1Eq2lAzs/POjE8D6Bj4dzwabfJjYQhV/i7/xDhwSDIQwMMUgsIa93MZoSb0OytbvcrTTqsnbxEYN+4nYtqSmVIfyN9kpPonRJrP8UgK6CorFFeHuNxCku2xpBnVNVKG032uFFe6+QFL+5Zsg+
  template:
    metadata:
      creationTimestamp: null
      name: accounts-ui-secret
      namespace: ory          
      annotations:
        helm.sh/hook: 'pre-install, pre-upgrade'
        helm.sh/hook-delete-policy: before-hook-creation
        helm.sh/hook-weight: '-1'
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keto-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQCkTl75YWzj/6vvpm4++AYgj8ihw5cLmv1Mo6PgvDVx7V+3bn6WzyXCUMY29oCEq9Gm8AWXlE6iaIeUTnQOMyqz0lip8jinxkf1yy22EeTP12pEQs7X6noGzr1CaaQYMhQAVqgXLe9y6uRVrWRrpZxAeXOMI9o8QDEOigmr6pflbpF/mx/oSPEWoInyGcqWRruoXiSSREHzdWQgShzCnc87P50Ze/sIp2XyzAFV6F7mpo3GrCm6kkQyOkcr5bFF2u8sXC5LSew4fZbX5tTcu5rX7kW/foNMqqlA7MoaKIA2xRgLc4enCX21om7OMr/ZOzIr45KdSlS0ybaOlAOsTNiUCO7XiYQV4KlCp432hU0I3IpgZw7XBHqRDo8wxaJiM9TMIlyFxUwcF/oyJNsomI3eW0jK4lfLWndDRUtxlKfcWD2rTT52pl/PqvfHQoIlgRrvZMJ+GQBxdG1nKOzLUK4+CjAZe5U/93U=
  template:
    metadata:
      creationTimestamp: null
      name: keto-secret
      namespace: ory

