---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ory
spec:
  encryptedData:
    admin-password: AQBE4ZlaFBn/hZyu/N9M9I0B1tdMrgQjwrjtDXV1p6jCRJC4WPH2OpWk2lpYKQIT5RgpHbRjwiScsPLKF6SFNOKTN33hr8ZuSEcMSOVorHSjhx80B0usWq9+SFUPRFmXWOmV9SRd07MSEFB+L5T+lPMVTHa7OdsLnWNF3RUgP+MfPIB+Z+/qWxH2VHQUoFtwniRNw9vIQEAMoDxF3Eoh1PsGx4Vc6+pmbEEIbUQzCJuarZSeYsW2F07KLdRpEWwRDaPo0UlzA/wWghFy1vCr4QeA8LG4zr/ow97AAb7oybYa7XXN3d0zPa/Oo0yvWsgXKDoSpHgw9+dOxN9GHpC2hZlWDrpNo9ubhsgPIw/NbJAzIjN2ESiJjwxCL/8aRZ4FNPNhrLdgq/OwNjTMY851pWt8vLWXRg==
    password: AQAqBWjWMlANR9NJLzwr+V7cWyNaGRhdiwHAPjPi0jcYA4IBMpL0nLUx8NumH8zGzU51yoSDjoHQYIUj/Btl9RKWPqxzBX36rdP+h35/PupZzI5Td8mD3Z+t+cQJNJvc/9Jc7jdgO9a/WpVUQ9gmyAKvmH4XR7IDeqHaEVkjMVvqk01OW5t9TJHfAa4VMro9l6F4akyNFnIJejuRNRjPHiVKBW9BjmWWEioS7WXgKDArfGWefCuBmsRsv6JmTmdlOA4KUnqFjf0Y+3JlFdPYlmz+YnHQREzPSh6t+i8raO7fpUGQx+jlmEV4hiZ2GsI1Ikwpbv9W606VoaHIx61/mZQvozBmkNYF3GdYELiab7oVUFfMtyzhnRlVu29fbWFfbUgnfWibeyKZH64EEuga82gW1aAj9g==
    replication-password: AQARYzMaJP9on8+jARWq4fwKr8EP19dtKPiVngQR+p9jP+mAtDObx0n3n/ElsQHWEE8fjPoMn3xXdGhwNj3Kf5UNcY9uLCmJueGrm4qN8+q9+ml8u2h0XQ9HZ7H36eQIL1Zd08sfqIaLw1+OkhZnygSYBLlZwbe0BcOJiJ3WQOJbLiT6TOxwQfTQB5Rv8yHS8RhvPthbVBlBNLzWf6J+4p62YjlBKMJ8sDXqtMPowBPlUcAmBgjb1JUj/HG+oBBnfmcnihvEeLFjF2JfJDhYI35AGskD6DF3L0gSoPckFR3xOi/ZILavm7CpZbdmYHrqJKU7z5mbsZSJiEnyLqtLbb38IKHagDC5QYvDRNhSg+j0Z18GzZX0VlxDxkk2rCDbZqbegOnijgNdvU8brmP0tlLFb8eOKQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: ory
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kratos-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQB9WyvSG/9IVE9gc2clsjzA+QeNiRKvcZ33QUlb6d/Cp92UVOGkxUA4fLZsyQtXTUlQRmRqWgBK4KMBqvnRb30WXfWM8qZKBwGTCyWTtlPAtZTgtpLuwsg1RNEeeZtnOomyTLO4M3MOWGEZKqha41ynErKBeUiduaTpNKBugwxuQGl4VCa1vxk+eRn2liM8qd/XC3MN6m76brn3ZR4ey5HHuiYP64Vg+ATGRvXa+8mPpYcUe3I0zKubVs07mbqM9sTGhPG5sUlfBGkE8fWgxHnscorgC7mnTj6ZXEIruDNThIkFhZN5/GYw/Be4xKSN2qP7SylhdSQ2x/nwA73ZG+Sh+KcHQDebus/4H2yp2S5kP662P6lf0HAgGiHs4u8Hs4nnSP3ex/ADe4F87oNHMKGoKxU/dLjzN0pkF0MUwzvl+DiOnUZvBwjOYF7wWIOnqaYtNIZj0U5ERJ6csfnQmmXsA1B02k7T5DRKZIYjbh1quXjiSSueBTl2an0d2US5eblucIk=
    secretsCipher: AQBpawhDWreFEbMyMOj+Dqv+8l+5ovC09SUJ59D/HCtSRZO6e9dBE5FQ45GTqTt1Y3klQXQNK+QeFjbkBIfrwHBudBp3pmDkxiZrYCApS/6yxhccyZaCv9eWtNVA4oxQIPm0pMMqtzb8HhSqOgRotZgMZULlLJbWcxQOyoDeqaJuV5ahxChwH25rTWsPUXpbFXxO13Wt6chCSSDTpC+/zoET9D6/3IC3r5YK0cN+bzpd8NpH9dt9k+xHpdPpdNMBb84sJL+phMHrqf3NM/GIXqAFT6yTnNOQch+kUQJriqmd4jcJ54Vl7c5GrJBwgiWq9UqeFG3iNww1xrTlN2zmXzpfuILsMV/sUY/YC5+ceihv4xqlAy8Lxx8BTYGeJtWDJnI4oIq6RS2kU/I9dfkvfbz3
    secretsCookie: AQCP8HhE/guA3GCM8p2APHLcZUmXVFj1bCZZx1q4XMvzDcHFy6/ee6naMUKQ+vZOYlGXdEyFY+sTP4WOPRm0i757vxZeVS0gBKTxDK9tLnmacZTovvmeFouJQz0XY6FtKK8Ln7Li9qVmluCphX4qkpdtVRgfXJ4h7I8Et41sFAVoOLwMzS3KBBCwXTFm7SSMsMWx+u0KV8KdewPf9BsjrXfNqhClkL11rUy047uFHuq/a4FTNX33QmVxtp2ic5KZRbAn0kf2suAJvHUElWEV3n09+j/ynQdsSBQnp0OxIZtszCGgeU3sYxaI4sE5LeN4Ijsp1d3n0W0TxoNBSmyKe3AdvHZj+r9tcCEWrdoNJLnK6P5vHExF1a/n1BM9WwSdK2Up+wMj+DQ80n4eFK57kp/V
    secretsDefault: AQBUNvY98akhSpkyvB5lPLql7d42Jqt+rdmH5i+Q+hML8NZ49hx19TWjZIyztwB7gu2PHYaxRqysrrmxEI8htufXUy6ksgwv0NpYkvlcpncYyEtSfP0tj6vWPMvxHJCTUqgt26qBAFWPCOfippcCi2581Vl+heBObZCfHN1k4iVqszKyi9O7xag8YcyQZsoS2VRqVSxxL0kRCgXLCnOsUARon7Q+ZqyxLtH/U0PmUOAXbDoeUAzFwxWgqhuVLcPdarshAtjuVMCOUEHlXGjPTONXLvhYubCdeCJ7rvU6/L+d+Wz7HcR8Rmi8KTC6La049bjfLzRQbJTrkzL3TuggSNChntOc+iWM+BwowjJqrs6ex3xEIhNsTKBIMdG6GwxRZHfcudMHoW24tj4p6Xj5DFke
    smtpConnectionURI: AQCQaOrQdej4G8OdJNYSxyLPKhlXbtM10sQyU9M0GfL2Inm/E2spEv2kvajaiTcY8qr8IgVPlEGdBMhf9YcULd57QXu5mtUcGQ+un73PBk8vxPz7i7pqKBtnuFWWkoU+3jvR4FYekXaQUuzE6JYgvLKwgRcHGUOJqWC05s7ek7gEmQrq6pTKS7wLCsURpiK2N8SbtTKZl1NTeWbULEG3/yWCjQGuh7N02jnNVoY0Z3u1fXmn3NaRwe/Mo5dhBda4bbiWZzjrmaMNLRu+8UCCUugQ7M50yorVnixXOwTwiLD0q+BavCsjYSLucTE6MKeLTbUX8ezcdtTzGZEpGtekz1ZW+0PegGf3RX+1GcwkRTT5JhVC9jjNZTLEZl3wMtSa/BSMX+Ae66qISP16Oisv6+Oj55wl3nggMYrDQrgDf3l4MgfqlvjRlmezXA==
  template:
    metadata:
      creationTimestamp: null
      name: kratos-secret
      namespace: ory
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hydra-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQCJnoWAOCZFnBiXiZhKcjqifjZVn2XpWKdVOwQpA7BZl32jrPEKaa+RoqcZyYkV7AXJrhlcw0cFNiGGrzNRAJZoc0Z54ULXPRJbyquxdGckaIeaRWesWUzTsqtJ7lOpbaCtQv1pDY3r6aGoAtdsee1ocDF/Ri+5uI2G7H6dE5MxGtlVvFBSJSCR4nWFOxM/SR7HmN88PrhG7sK2M6eRD3ezVKhTxAbNsZ3HNRg/2mNUMvbQYOrv7wusARH7m9QCIMfTFSvyO22FCxs8T8TUVkjkt+zUC2jfZ2UP4wiosRrMkWXgHQiqLssdQq2VDzhWQ/UZAkjEVYABu04pr0WA9dIl/3VXsw56rnIllhIgEhX7DX32+HxPNKIC08KnJPXHIUk+U3QZ2Msh4UMSuUutB3cftfRFWzzdc8efmuUlek8Rbq31UV8Ncx4GezorKcu75lPgM38uBH8ar5np/7rdJX1Bny8d7uLkjXeVkqMgj+CB1DM8uN1obbThd9YmWYmTSbFNwg==
    secretsCookie: AQAP+zDZhTAIsaHMWb9x3MSw/vr8gXbsRSnd3KwjOBNtd7vfAzj86lVufGzIFDuU98vr+pLYJWO96SIL4AnsNz0VJKSOzU17R2tlYJmOxPqs5PEX+Sl5FK4J/30At8mMkTf0fsy9bI/BrV3K9Y4818q3Kc7A/GAGht1VbMomMCbPaMRfV9v2xe02N8XeY09Skcb56ME9lsU1l2GR/rfiQ6wqt7xIyfNTyEILVHDrk5AaluYRQimwCf+U3eIHq3o9N8aS8WK4nEfzu3y8BFWrjuaihwi8Y9EzXVAGcQWb9t0Fzhk+FBwe1gOw6j0bFTzQZksexqOT1C5y3/5sv9nQdalCpOAV+KMQbwCAPYicCT3z7cjY5M1iMDHsA9qS/IjcZiVjc8tuGYle+3T4ZLKzXxk0
    secretsSystem: AQChMvKPc3AvCcBC0x0FS1PeYbopyc88nOiJlesrsFaNKMPiE7dtVXcjQo6DmDyOd2NHlZR2/y1l8+94OOi1Xyf7bymkVxOSH23bT0NLkG+6KzvLm9c7XjOv36fehWMakJw1ADPi/hQJMSo3XoQTFeUIkE9tN5w7C4ytmPM/yq8SpgZY138Avfn4I6ys1+IO+hDg6XS9sXwkeuUWCJJrD7o+hfADP94vrKZUfkpV3MC/2JNE822bcZSvin6o0gXJNFnx2aJt/5PReeVZ7Oqv1F9tUL/I//NMj0v74vzJK+Ya/rP721/TbMmBXztJeIrP/xtFjCVC80kjlYI4a1Kh55oqJTlidGfbNwLpcr2FLbmZvDhTcYNNJtvj/oyUfzFmwDpSiq5lLmhStTBH42/CJs6U
  template:
    metadata:
      creationTimestamp: null
      name: hydra-secret
      namespace: ory