apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-real-ip
  namespace: traefik
spec:
  headers:
    customRequestHeaders:
      X-Real-IP: "{CF-Connecting-IP}"
      X-Forwarded-For: "{CF-Connecting-IP}"