---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hydra-secret
  namespace: ory
spec:
  encryptedData:
    dsn: AQCJnoWAOCZFnBiXiZhKcjqifjZVn2XpWKdVOwQpA7BZl32jrPEKaa+RoqcZyYkV7AXJrhlcw0cFNiGGrzNRAJZoc0Z54ULXPRJbyquxdGckaIeaRWesWUzTsqtJ7lOpbaCtQv1pDY3r6aGoAtdsee1ocDF/Ri+5uI2G7H6dE5MxGtlVvFBSJSCR4nWFOxM/SR7HmN88PrhG7sK2M6eRD3ezVKhTxAbNsZ3HNRg/2mNUMvbQYOrv7wusARH7m9QCIMfTFSvyO22FCxs8T8TUVkjkt+zUC2jfZ2UP4wiosRrMkWXgHQiqLssdQq2VDzhWQ/UZAkjEVYABu04pr0WA9dIl/3VXsw56rnIllhIgEhX7DX32+HxPNKIC08KnJPXHIUk+U3QZ2Msh4UMSuUutB3cftfRFWzzdc8efmuUlek8Rbq31UV8Ncx4GezorKcu75lPgM38uBH8ar5np/7rdJX1Bny8d7uLkjXeVkqMgj+CB1DM8uN1obbThd9YmWYmTSbFNwg==
    secretsCookie: AQAP+zDZhTAIsaHMWb9x3MSw/vr8gXbsRSnd3KwjOBNtd7vfAzj86lVufGzIFDuU98vr+pLYJWO96SIL4AnsNz0VJKSOzU17R2tlYJmOxPqs5PEX+Sl5FK4J/30At8mMkTf0fsy9bI/BrV3K9Y4818q3Kc7A/GAGht1VbMomMCbPaMRfV9v2xe02N8XeY09Skcb56ME9lsU1l2GR/rfiQ6wqt7xIyfNTyEILVHDrk5AaluYRQimwCf+U3eIHq3o9N8aS8WK4nEfzu3y8BFWrjuaihwi8Y9EzXVAGcQWb9t0Fzhk+FBwe1gOw6j0bFTzQZksexqOT1C5y3/5sv9nQdalCpOAV+KMQbwCAPYicCT3z7cjY5M1iMDHsA9qS/IjcZiVjc8tuGYle+3T4ZLKzXxk0
    secretsSystem: AQChMvKPc3AvCcBC0x0FS1PeYbopyc88nOiJlesrsFaNKMPiE7dtVXcjQo6DmDyOd2NHlZR2/y1l8+94OOi1Xyf7bymkVxOSH23bT0NLkG+6KzvLm9c7XjOv36fehWMakJw1ADPi/hQJMSo3XoQTFeUIkE9tN5w7C4ytmPM/yq8SpgZY138Avfn4I6ys1+IO+hDg6XS9sXwkeuUWCJJrD7o+hfADP94vrKZUfkpV3MC/2JNE822bcZSvin6o0gXJNFnx2aJt/5PReeVZ7Oqv1F9tUL/I//NMj0v74vzJK+Ya/rP721/TbMmBXztJeIrP/xtFjCVC80kjlYI4a1Kh55oqJTlidGfbNwLpcr2FLbmZvDhTcYNNJtvj/oyUfzFmwDpSiq5lLmhStTBH42/CJs6U
  template:
    metadata:
      creationTimestamp: null
      name: hydra-secret
      namespace: ory
