apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: argocd-realm
  namespace: argocd
  labels:
    app: argocd
spec:
  realm:
    realm: argocd
    enabled: true
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: argocd-client
  namespace: argocd
spec:
  realmSelector:
    matchLabels:
      app: argocd
  client:
    clientId: argocd
    name: ArgoCD
    publicClient: true
    redirectUris:
      - "https://argocd.ecoma.io/auth/callback"
    webOrigins:
      - "*" 
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: true
    protocol: openid-connect
    attributes:
      pkce.code.challenge.method: "S256"  # Bắt buộc sử dụng PKCE