apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  commonName: accounts.ecoma.io
  dnsNames:
    - accounts.ecoma.io