apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgresql-hl.keycloak.svc.cluster.local
    database: keycloak
    usernameSecret:
      name: keycloak-database-secret
      key: database-username
    passwordSecret:
      name: keycloak-database-secret
      key: database-password    
    poolInitialSize: 1
    poolMinSize: 1
    poolMaxSize: 3
  http:
    httpEnabled: true
  hostname:
    strict: false
    hostname: accounts.ecoma.io
  ingress:
    enabled: false
  transaction:
    xaEnabled: false
  additionalOptions:
    - name: proxy-headers
      value: xforwarded

---

apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: argocd-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    id: ecoma
    realm: ecoma
    displayName: Ecoma
    enabled: true
    registrationAllowed: true
    registrationEmailAsUsername: true
    loginWithEmailAllowed: true
    rememberMe: true
    clients:
      - clientId: argocd
        name: ArgoCD
        description: ArgoCD
        enabled: true
        clientAuthenticatorType: client-secret
        directAccessGrantsEnabled: true
        standardFlowEnabled: true
        serviceAccountsEnabled: true        
        publicClient: false
        secret: "${ARGOCD_CLIENT_SECRET}"
        redirectUris:
          - "https://argocd.ecoma.io/*" 
        webOrigins:
          - "+"
        protocol: openid-connect
        attributes:
          access.token.lifespan: "3600"
        defaultClientScopes:
          - profile
          - email
          - roles
    users:
      - username: admin
        enabled: true
        firstName: Argo
        lastName: Admin
        email: admin@example.com
        emailVerified: true
        realmRoles:
          - realm-admin
    identityProviders:
      - alias: github
        providerId: github
        enabled: true
        config:
          clientId: Ov23li943a6yVEZruicm
          clientSecret: "${GITHUB_CLIENT_SECRET}"
          defaultScope: "read:user user:email"      
      - alias: google
        providerId: google
        enabled: true
        config:
          clientId: 49648312556-mpvuf5030bpt6qlqevv1lit8c3uu5b2l.apps.googleusercontent.com
          clientSecret: "${GOOGLE_CLIENT_SECRET}"
          defaultScope: "read:user user:email"
    placeholders:
      ARGOCD_CLIENT_SECRET:
        secret:
          name: keycloak-clientid-secret
          key: argocd
      GITHUB_CLIENT_SECRET:
        secret:
          name: keycloak-clientid-secret
          key: github
      GOOGLE_CLIENT_SECRET:
        secret:
          name: keycloak-clientid-secret
          key: google