apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgresql-hl.keycloak.svc.cluster.local
    database: keycloak
    usernameSecret:
      name: keycloak-database-secret
      key: database-username
    passwordSecret:
      name: keycloak-database-secret
      key: database-password    
    poolInitialSize: 1
    poolMinSize: 1
    poolMaxSize: 3
  http:
    httpEnabled: true
  hostname:
    strict: false
    hostname: accounts.ecoma.io
  ingress:
    enabled: false
  transaction:
    xaEnabled: false
  additionalOptions:
    - name: proxy-headers
      value: xforwarded

---

apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: argocd-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    id: ecoma
    realm: ecoma
    displayName: Ecoma
    enabled: true
    registrationAllowed: true
    registrationEmailAsUsername: true
    loginWithEmailAllowed: true
    rememberMe: true
    clients:
      - clientId: argocd
        name: ArgoCD
        description: ArgoCD
        enabled: true
        clientAuthenticatorType: client-secret
        directAccessGrantsEnabled: true
        standardFlowEnabled: true
        serviceAccountsEnabled: true        
        publicClient: false
        fullScopeAllowed: true
        secret: "${ARGOCD_CLIENT_SECRET}"
        redirectUris:
          - "https://argocd.ecoma.io/*" 
        webOrigins:
          - "+"
        protocol: openid-connect
        attributes:
          access.token.lifespan: "3600"
        defaultClientScopes:
          - profile
          - email
          - roles
        roles:
          - name: admin
            description: "Administrator role for ArgoCD"
    users:
      - username: john.itvn@gmail.com
        enabled: true
        firstName: Argo
        lastName: Admin
        email: john.itvn@gmail.com
        emailVerified: true
        realmRoles:
          - realm-admin
        clientRoles:
          argocd:
            - admin
    identityProviders:
      - alias: github
        providerId: github
        enabled: true
        trustEmail: true
        config:
          clientId: Ov23li943a6yVEZruicm
          clientSecret: "${GITHUB_CLIENT_SECRET}"
        syncMode: "INHERIT"
        mappers:
          - name: github-email-mapper
            identityProviderMapper: oidc-user-attribute-idp-mapper
            config:
              claim: email
              user.attribute: email
              syncMode: "FORCE" 
          - name: github-fullname-mapper
            identityProviderMapper: oidc-user-attribute-idp-mapper
            config:
              claim: name
              user.attribute: fullName
              syncMode: "INHERIT"
          - name: github-avatar-mapper
            identityProviderMapper: oidc-user-attribute-idp-mapper
            config:
              claim: picture
              user.attribute: avatar
              syncMode: "INHERIT"
          - name: github-id-mapper
            identityProviderMapper: oidc-user-attribute-idp-mapper
            config:
              claim: sub
              user.attribute: external-github-id
              syncMode: "FORCE"
      - alias: google
        providerId: google
        enabled: true
        trustEmail: true
        config:
          clientId: 49648312556-mpvuf5030bpt6qlqevv1lit8c3uu5b2l.apps.googleusercontent.com
          clientSecret: "${GOOGLE_CLIENT_SECRET}"
        syncMode: "INHERIT"
        mappers:
          - name: google-email-mapper
            identityProviderMapper: oidc-user-attribute-idp-mapper
            config:
              claim: email
              user.attribute: email
              syncMode: "FORCE"
          - name: google-fullname-mapper
            identityProviderMapper: oidc-user-attribute-idp-mapper
            config:
              claim: name
              user.attribute: fullName
              syncMode: "INHERIT"
          - name: google-avatar-mapper
            identityProviderMapper: oidc-user-attribute-idp-mapper
            config:
              claim: picture
              user.attribute: avatar
              syncMode: "INHERIT"
          - name: google-id-mapper
            identityProviderMapper: oidc-user-attribute-idp-mapper
            config:
              claim: sub
              user.attribute: external-google-id
              syncMode: "FORCE"
  placeholders:
    ARGOCD_CLIENT_SECRET:
      secret:
        name: keycloak-clientid-secret
        key: argocd
    GITHUB_CLIENT_SECRET:
      secret:
        name: keycloak-clientid-secret
        key: github
    GOOGLE_CLIENT_SECRET:
      secret:
        name: keycloak-clientid-secret
        key: google