apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-database-secret
  namespace: keycloak
spec:
  encryptedData:
    database-password: AQCGMfjQSOT0HPVWX70BKTb6vLFh2O9X58oencB/jGsUDD/KKRXlu2xi8V3qsVhDhBY01NdYffkKMwkpRoxBIRcSRFtUHeeOBh2EQi/xl74OY7NPaGHLHULKyIZUbggvaMN/ZSXpBrjUxnTg/EwoPtrAgxyrPDWM+9TGGiLLL0lIOogkQGo21CL6JYhA2MqPDOmeIcskqHF9jcSIRjfTbfzyQoHaigHOjYpqjN0y6/WAveRYgpK/Qb/SzoYUyMToF46zkx/UUHE0pkwMNFrs37ZtvA4WnE9IC7HTsTFbE6uaDqESkmasyTQdxMS/+tf9LgUgD6RYTN7Y+PPOe5H6y7YO1bJtqexCIX4mLCnGXqmVSZDXeDPDLcK0zaRRQxNEVC78PDpWSLMs7RCwDm6ZBW4U
    database-username: AQBV1r4P9EbtN4HSu89fvQTU4nlepiX90ctrFwDqnQbixbe3C8LwVKRq8ISoolfrR5QO00cvFqKUoowEFtTdsxVKobidgvM3Y6AfubKASqw1NmY/cBtbhoSxtir03O4Mf9wiF0SlKkm0qrfxYgcz2EJf3vqk8tF6TYsTvMgR9NrLgJksgNamRCO2wGKQqtO3LOYvt2KtMX4tEojA4dfVv0gvUSUQxdR6SuiUjfJDpQhWdegQzhUQi81ZX1aRsbv31YIqclSIdm68L0T0gkDBhpXS09JWeU16kbPgtoEFMjLKJL6x7DQWhVPN8yqUW/RKLstSjn05nINuIyBJYTVSxTHp/ipLVL6CeuuxHGB8HbgWysYPEeaUBM01
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-database-secret
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-clientid-secret
  namespace: keycloak
spec:
  encryptedData:
    argocd: AQBoZ44xQnmTrMEQHUWtlNUpbSZtBKwuhXVREnzJnHev3k2mRx28u3H60p2+DkVP8HN8NA4uzTLtvO+DG65e4p/6uS/zsGK+8JTUsYrP2/6tXYJUkfG1G5QioBXAuOFTAM84b5oE+JD/ApYVWB7yfeR3dMVbVbnzyOXkmcAvbp48g5nzbMXmURr7RF6KIxOnMROrpbWFGfx6biJMtJFyJWM2MTWFfC36e671aPpPP/QyjIhXVpVK5fHLma0VjoZT64o6jDHlXOxTnXlGgWRpqBH1GZfvo199iJgQIV88+gdCF0g+Gf7UuKSs4X9lMVd6lUNCRJSG3vhQ5QQhsTuMp1P6avQHS+2fg9aXhQ3EQgsDw4BUUuzj8JLjso29PuifmlywyWNoxMIxMPS9tmQY+Sy3+iRy2Q4WJxhNZkMupGCE6mYV
    github: AQA17TmqWUGbeF/+VOrD6DUyxVaVlsIsYeoqxA9M8fuws2C33/z+aTNyjZGlSytv0exZ+5YTApTj0uWarMqfNrwqiLbpDN+G4+e+3kW5p5gjpOjnWqHXZWDYk3RUA5bJTjiZsI2VALdIx2UeRifCPkOoQbGHFIrOieUYE+nEdezxBNmb3iwS/+Xlmu9DSBZVO/GYAsBa59rCnbLiWlP5g39N5c3ZdzdZzvL3mldux4+mrauRyU+aNslk45MX4I+/o5uCPY4llk9oNGO8ELkBVbml1g4bEMPCoqMUVIBFXyLfa1g4BOP2yb04nElhoyoSs7NPjrlEo+F+kOmawpdLJHj5BxZTAmpPesb5dgpNsfF2gOa1gpes7uZjshEQZushshjn830x9qEE+zkZmIadCIJnjLgT8i+vW5Q=
    google: AQAcuSgoavSe01DvQl386ssoWukGUcAQxDL9wVGo3Zbr7w7Yz39zxKwWk6TRWvPdGglCTcBQleOPYR7AzsZ4MqdsBXLoi2w+nSpKYtq50PwplnGs5rpFbJpxcx7m5lNonvKko9aAarLBLy5/E45Cf+6OAfTpoXI8CkRptWz5B0hy8PYud9bzZveRLqmBclVY7TTpmcPwfkFbznR2VGiOeaDNXLIGKg2gGPTqpU433FYYaJ+eSMKHoJO0pGBPWB1G3h9N0P5pZjgQToLsujqImDexP6LMK30fasnFjabZ1om1YJ/CAWkhFz8AWhBqyD135a+/UDQqvX2gay24L5N0ggxGajGBGv/oh1/JTeD+MVhBcgvYatM+ppYDdqWkFlys09XbX7Ql1V6rMo0U4fxx7kYi4tAO
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-clientid-secret
      namespace: keycloak