apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-database-secret
  namespace: keycloak
spec:
  encryptedData:
    database-password: AQCOTU12Hs3Mg02sWJckCvAhVmX/N7Z98Z/NgjKMR1Uf3nqAHCJJSEZwqsLLZLmv0eXFDggaxx/mv6uE6ag6x6qY6WS+VuDAHE6o7BhU5ddpV3VmMqF+9Ln+gE5zVg09bIsF5OHe1+uJv6UvB/aXjSIqcG9u3IKHPeo2mC1ZolcpjcuJ5CWJONy08MnqHTGgGjUBJDMt0LBUYvTDCmvzouRTnQRUksTobNARBxOh5+lUfbfXIU2oAHTGXjXiwRFPWgDmpWhEMI3XBH7Gidf1yrQJfzAh6m8gurhiAmbbD5vULmMK/Oi33nTLddXvX1ff5SRW7qL1/UcnKVwlNlAnt/L4vaXLW21CLBc1BcKzrAX33ETAqUm8COW34gtc
    database-username: AQCPxJApWBMyEMHTEvyZx7W54NNy0rf8ITfMBhLfUIn/FdMoYLCfSrh0yFcx2sz+WmdDRnPdfpT5GreFGqxF6uLg0+luENkg43Kqco1QygEAJDU/Uv03uoWHYkbGV7OCqFCsrAW80GajiqGsSC55XWaMVblxkQGs0l3+Bb6We8iNTS5u0tghAjAAcDmBGaUkRWBglet1WxQYM0pzanKOKza4DAHs0sTF9O8hh5m5bRfbc62SWTGsxgm3ycXN9teLBrS2mN5w2GOxKxg0iqvN6Wx0OAU5B0Psg8sTcwWYza8QxcPtXF3zn18Z8w113XkOixt+wUXPpK0cEFzNHeG1sGITjGjY5LeKQhdj/n5PbWdMunoMXh7H9D0u3j0yVYdfAfD9KCZ/IApBnNdj5AHzpUFQ
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-database-secret
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-clientid-secret
  namespace: keycloak
spec:
  encryptedData:
    argocd: AQBoZ44xQnmTrMEQHUWtlNUpbSZtBKwuhXVREnzJnHev3k2mRx28u3H60p2+DkVP8HN8NA4uzTLtvO+DG65e4p/6uS/zsGK+8JTUsYrP2/6tXYJUkfG1G5QioBXAuOFTAM84b5oE+JD/ApYVWB7yfeR3dMVbVbnzyOXkmcAvbp48g5nzbMXmURr7RF6KIxOnMROrpbWFGfx6biJMtJFyJWM2MTWFfC36e671aPpPP/QyjIhXVpVK5fHLma0VjoZT64o6jDHlXOxTnXlGgWRpqBH1GZfvo199iJgQIV88+gdCF0g+Gf7UuKSs4X9lMVd6lUNCRJSG3vhQ5QQhsTuMp1P6avQHS+2fg9aXhQ3EQgsDw4BUUuzj8JLjso29PuifmlywyWNoxMIxMPS9tmQY+Sy3+iRy2Q4WJxhNZkMupGCE6mYV
    github: AQA17TmqWUGbeF/+VOrD6DUyxVaVlsIsYeoqxA9M8fuws2C33/z+aTNyjZGlSytv0exZ+5YTApTj0uWarMqfNrwqiLbpDN+G4+e+3kW5p5gjpOjnWqHXZWDYk3RUA5bJTjiZsI2VALdIx2UeRifCPkOoQbGHFIrOieUYE+nEdezxBNmb3iwS/+Xlmu9DSBZVO/GYAsBa59rCnbLiWlP5g39N5c3ZdzdZzvL3mldux4+mrauRyU+aNslk45MX4I+/o5uCPY4llk9oNGO8ELkBVbml1g4bEMPCoqMUVIBFXyLfa1g4BOP2yb04nElhoyoSs7NPjrlEo+F+kOmawpdLJHj5BxZTAmpPesb5dgpNsfF2gOa1gpes7uZjshEQZushshjn830x9qEE+zkZmIadCIJnjLgT8i+vW5Q=
    google: AQAcuSgoavSe01DvQl386ssoWukGUcAQxDL9wVGo3Zbr7w7Yz39zxKwWk6TRWvPdGglCTcBQleOPYR7AzsZ4MqdsBXLoi2w+nSpKYtq50PwplnGs5rpFbJpxcx7m5lNonvKko9aAarLBLy5/E45Cf+6OAfTpoXI8CkRptWz5B0hy8PYud9bzZveRLqmBclVY7TTpmcPwfkFbznR2VGiOeaDNXLIGKg2gGPTqpU433FYYaJ+eSMKHoJO0pGBPWB1G3h9N0P5pZjgQToLsujqImDexP6LMK30fasnFjabZ1om1YJ/CAWkhFz8AWhBqyD135a+/UDQqvX2gay24L5N0ggxGajGBGv/oh1/JTeD+MVhBcgvYatM+ppYDdqWkFlys09XbX7Ql1V6rMo0U4fxx7kYi4tAO
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-clientid-secret
      namespace: keycloak