apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-database-secret
  namespace: keycloak
spec:
  encryptedData:
    database-password: AQCOTU12Hs3Mg02sWJckCvAhVmX/N7Z98Z/NgjKMR1Uf3nqAHCJJSEZwqsLLZLmv0eXFDggaxx/mv6uE6ag6x6qY6WS+VuDAHE6o7BhU5ddpV3VmMqF+9Ln+gE5zVg09bIsF5OHe1+uJv6UvB/aXjSIqcG9u3IKHPeo2mC1ZolcpjcuJ5CWJONy08MnqHTGgGjUBJDMt0LBUYvTDCmvzouRTnQRUksTobNARBxOh5+lUfbfXIU2oAHTGXjXiwRFPWgDmpWhEMI3XBH7Gidf1yrQJfzAh6m8gurhiAmbbD5vULmMK/Oi33nTLddXvX1ff5SRW7qL1/UcnKVwlNlAnt/L4vaXLW21CLBc1BcKzrAX33ETAqUm8COW34gtc
    database-username: AQCPxJApWBMyEMHTEvyZx7W54NNy0rf8ITfMBhLfUIn/FdMoYLCfSrh0yFcx2sz+WmdDRnPdfpT5GreFGqxF6uLg0+luENkg43Kqco1QygEAJDU/Uv03uoWHYkbGV7OCqFCsrAW80GajiqGsSC55XWaMVblxkQGs0l3+Bb6We8iNTS5u0tghAjAAcDmBGaUkRWBglet1WxQYM0pzanKOKza4DAHs0sTF9O8hh5m5bRfbc62SWTGsxgm3ycXN9teLBrS2mN5w2GOxKxg0iqvN6Wx0OAU5B0Psg8sTcwWYza8QxcPtXF3zn18Z8w113XkOixt+wUXPpK0cEFzNHeG1sGITjGjY5LeKQhdj/n5PbWdMunoMXh7H9D0u3j0yVYdfAfD9KCZ/IApBnNdj5AHzpUFQ
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-database-secret
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-clientid-secret
  namespace: keycloak
spec:
  encryptedData:
    argocd: AQBdqXVgrcgFFlGV6Qidu91qIpggQ327f8+32++xn7rqwi2/PO3INf7pxHlsxVO6blnwwafYk/qB3tECOveW2qFJ/ZV3ctuTQnshvk2M+qxrv9RdyUuOHDRzeWCdJsDF9pWVHiw2ZtPwMQMp1vwA02Umi3eJUuPtEUJTZON3w/Kbhr+rvHbgY2lXeQVEvWFt7k4trpUu5uCvEspMNbdOJ870INvDrFABEML2QxDrzFrEQqRDPjH5Avqnh7iExyxqE0ViXLk6tjS8BJraIpyRNsGQxL2fWcreTp+h7TaH2+rsXyskJ65wMkXQibwjsfTTeUddQ+7eVe/Z9g3eSoMMueKqrVvp5qJnaINxqoblEPVvVfBsLcNMX+UTHNf6tUY8PnTQ6majeFy6/oFabKvSkFttvVqeEyPVw7/I1GXU3Y+dFZO0
    github: AQAUl0X2TSGsnqtLSP+uNrkUdy3wRaSho7FN40+V67F817wExEdAnwO8LZXHMF8VZ4UjbOXuODPh41UIYrtNa6+KAmzmOtATZbuqjXBogTMgNmqXJr9ILEpHkrchxddnpN6G4PX6gX1Q1LaK+qO6R3NnSa1zMqiGEbBxWIBqqTFTAOcwPNUTwUsqcQanHfQpMmh4yk/FP7uNI3pl+9wNmXrkx/jL1RlQfU1ztoW0kNIs3aHt8vPIdVxht9lJzBW75JFtNs2DjdUyADHWLGySZzY7Apn1YoJpXz585mPZa/hjGFOsuu1DkZZWqynEah7NBe0kiG3GWPuKcPahVdhEZide2zXwtc1ghXW6HbFw1JukmpbGCdQUVsj6/xd1PcR3K/zVqzqP5sLN2SIs5BFyiVsl2dDRymnMd18=
    google: AQCWpiOCaUPjZEaTTktTteoNYNjWqbiiadlV/I2l+aKmjc4BWyTku4cJ/JKFe1S/9Uebwy/ciSZU6umi/B+/KZPXW1lN+3CB4PiQe8cfi0rHr+ed/53v7tan7SqpF6QyRXq55ZSsi2biawSPsk76E2yDhMNC9xs8+1nGYxrqmdyMHopKcma8Zd5nKCazbxaKBWCHqKcr+JOZIQaLDHBCqQKWcvcPqgOdLxuK++SlBF/K2uv7he30HqQeMIqtNZw1lux4LAKM2z0YvJevM75Y/W5gHcFEtZlJeGVzYK6K2hteyDbXB7Ax6WXMmCmztJ3wUsBCBdvisPcDR+UVlGehY+yLi+Bdb/EDo0/lZsmdAcxxPm+yZXBPnFCfywX/9A26P8mppbk2LAVC6I5ZgmJczp1qNt6a
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-clientid-secret
      namespace: keycloak
