postgresql:
  fullnameOverride: postgresql
  architecture: standalone
  auth:
    username: keycloak  
    database: keycloak
    existingSecret: keycloak-postgresql-secret
    secretKeys:      
      userPasswordKey: password
      adminPasswordKey: admin-password
      replicationPasswordKey: replication-password
  primary:    
    nodeSelector: 
      kubernetes.io/hostname: node1
    persistence:
      enabled: false
      size: 1Gi
      storageClass: local-path
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 768Mi
