apiVersion: v1
kind: Namespace
metadata:
  name: ecoma-internal
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
  labels:
    app.kubernetes.io/name: ecoma-internal
  name: ecoma-internal
  namespace: ecoma-internal
spec:
  project: default
  source:
    path: chart
    repoURL: https://github.com/ecoma-io/internal.git
  destination:
    namespace: ecoma-internal
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
