kratosdb:
  fullnameOverride: kratosdb
  architecture: standalone
  auth:
    username: kratos  
    database: kratos
    existingSecret: postgresql-secret
    secretKeys:      
      userPasswordKey: password
      adminPasswordKey: admin-password
      replicationPasswordKey: replication-password
  primary:    
    nodeSelector: 
      kubernetes.io/hostname: node1
    persistence:
      size: 1Gi
      storageClass: local-path
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 768Mi

hydradb:
  fullnameOverride: hydradb
  architecture: standalone
  auth:
    username: hydra  
    database: hydra
    existingSecret: postgresql-secret
    secretKeys:      
      userPasswordKey: password
      adminPasswordKey: admin-password
      replicationPasswordKey: replication-password
  primary:    
    nodeSelector: 
      kubernetes.io/hostname: node1
    persistence:
      size: 1Gi
      storageClass: local-path
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 768Mi

ketodb:
  fullnameOverride: ketodb
  architecture: standalone
  auth:
    username: keto  
    database: keto
    existingSecret: postgresql-secret
    secretKeys:      
      userPasswordKey: password
      adminPasswordKey: admin-password
      replicationPasswordKey: replication-password
  primary:    
    nodeSelector: 
      kubernetes.io/hostname: node1
    persistence:
      size: 1Gi
      storageClass: local-path
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 768Mi

kratos:
  fullnameOverride: kratos
  replicas: 1
  nodeSelector: 
    kubernetes.io/hostname: node1
  kratos:
    config:
      cookies:
        domain: ecoma.io
        path: /
        same_site: Lax
      session:
        cookie:          
          domain: ecoma.io
          path: /
          same_site: Lax
      identity:
        default_schema_id: default
        schemas:
          - id: default
            url: file:///etc/config/identity.default.schema.json
      selfservice:
        default_browser_return_url: https://accounts.ecoma.io/
        flows:
          login:
            ui_url: "https://accounts.ecoma.io/login"
            after:
              default_browser_return_url: https://accounts.ecoma.io/
              oidc:
                default_browser_return_url: https://accounts.ecoma.io/
          registration:
            ui_url: "https://accounts.ecoma.io/registration"
            after:
              default_browser_return_url: https://accounts.ecoma.io/
              oidc:
                default_browser_return_url: https://accounts.ecoma.io/
          recovery:
            enabled: true
            ui_url: "https://accounts.ecoma.io/recovery"
            after:
              default_browser_return_url: https://accounts.ecoma.io/
          verification:
            enabled: true
            ui_url: "https://accounts.ecoma.io/verification"
            after:
              default_browser_return_url: https://accounts.ecoma.io/
          settings:
            ui_url: "https://accounts.ecoma.io/settings"
            after:
              default_browser_return_url: https://accounts.ecoma.io/
          error:
            ui_url: "https://accounts.ecoma.io/error"

        methods:
          password:
            enabled: true
          
          oidc:
            enabled: true
            config:
              providers:
                - id: github
                  mapper_url: "file:///etc/social-providers-config/github.jsonnet"
                  provider: github
                  client_id: Ov23li943a6yVEZruicm
                  client_secret: ${GITHUB_CLIENT_SECRET}
                  scope:
                    - read:user
                    - user:email
                  requested_claims:
                    id_token:
                      email:
                        essential: true
                      full_name:
                        essential: true
                - id: google
                  mapper_url: "file:///etc/social-providers-config/google.jsonnet"
                  provider: google
                  client_id: 49648312556-mpvuf5030bpt6qlqevv1lit8c3uu5b2l.apps.googleusercontent.com
                  client_secret: ${GOOGLE_CLIENT_SECRET}
                  scope:
                    - openid
                    - profile
                    - email
    automigration:
      enabled: true
    identitySchemas:
      "identity.default.schema.json": |
        {
          "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "Person",
          "type": "object",
          "properties": {
            "traits": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email",
                  "title": "E-Mail",
                  "ory.sh/kratos": {
                    "credentials": {
                      "password": {
                        "identifier": true
                      }
                    },
                    "recovery": {
                      "via": "email"
                    },
                    "verification": {
                      "via": "email"
                    }
                  }
                },
                "full_name":{
                  "type":"string",
                  "title":"Full Name"
                }
              },              
              "required": [
                "email",
                "full_name"
              ],
              "additionalProperties": false
            }
          }
        }
  deployment:
    extraVolumes:
      - name: social-providers-cm
        configMap:
          name: social-providers-cm
    extraVolumeMounts:
      - name: social-providers-cm
        mountPath: /etc/social-providers-config
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: kratos-secret
            key: dsn
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: kratos-secret
            key: github-client-secret
      - name: GOOGLE_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: kratos-secret
            key: google-client-secret
  statefulSet:
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: kratos-secret
            key: dsn
  job:
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: kratos-secret
            key: dsn
  cronjob:
    cleanup:
      extraEnv:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: kratos-secret
              key: dsn
  secret:
    enabled: false
    nameOverride: kratos-secret
  ingress:
    public:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: kratos-public.ecoma.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: kratos-public-tls
          hosts:
            - kratos-public.ecoma.io
    admin:
      enabled: true
      className: traefik      
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: kratos-admin.ecoma.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: kratos-admin-tls
          hosts:
            - kratos-admin.ecoma.io  

kratos-ui:
  fullnameOverride: accounts-ui
  config:
    csrfCookieName: ecoma-x-csrf-token
  secret:
    enabled: false
    nameOverride: accounts-ui-secret
  kratosPublicUrl: "https://kratos-public.ecoma.io"
  kratosAdminUrl: "https://kratos-admin.ecoma.io"
  kratosBrowserUrl: "https://kratos-public.ecoma.io"
  # jwksUrl: "http://oathkeeper-api"
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: cluster-issuer
    hosts:
      - host: accounts.ecoma.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
        - accounts.ecoma.io
      secretName: accounts-ui-tls
  
hydra:
  fullnameOverride: hydra
  hydra-maester:
    adminService:
      name: hydra-admin
  hydra:
    automigration:
      enabled: true  
    config:
      urls:
        self:
          issuer: "https://authorize.ecoma.io/"   
        login: https://kratos.ecoma.io/login
        logout: https://kratos.ecoma.io/logout
        registration: https://kratos.ecoma.io/registration     
        consent: https://accounts.ecoma.io/consent
        identity_provider:
          url: https://accounts.ecoma.io/app        
  secret:
    enabled: false
    nameOverride: hydra-secret
  deployment:
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: hydra-secret
            key: dsn
  ingress:
    public:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: hydra-public.ecoma.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - hosts:
          - hydra-public.ecoma.io
        secretName: hydra-public-tls
    admin:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: hydra-admin.ecoma.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - hosts:
          - hydra-admin.ecoma.io
        secretName: hydra-admin-tls 

keto:
  fullnameOverride: keto
  keto:
    automigration:
      enabled: true
  deployment:
    nodeSelector: 
      kubernetes.io/hostname: node1
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: keto-secret
            key: dsn
  ingress:
    read:
      className: traefik
      hosts:
        - host: keto.ecoma.io
          paths:
            - path: /read
              pathType: Prefix
      tls:
      - hosts:
          - keto.ecoma.io
        secretName: keto-tls 
    write:
      className: traefik
      hosts:
        - host: keto-write.ecoma.io
          paths:
            - path: /write
              pathType: Prefix
      tls:
      - hosts:
          - keto.ecoma.io
        secretName: keto-tls 

oathkeeper:
  fullnameOverride: oathkeeper
  oathkeeper:
    config:
      # authorizers:
      #   allowed:
      #     handler: allow
      #   deny:
      #     handler: deny
      # authenticators:
      #   jwt:
      #     jwks_urls:
      #       - http://sentinel-api/.well-known/jwks.json
      #     rule:
      #       allowed_algorithms:
      #         - RS256
      #       required_scope: ["openid"]
      #       required_audience: ["oathkeeper-api"]
      #       required_issuer: "https://kratos.ecoma.io/"
      # rules:
      #   - id: allow
      #     description: "Allow all requests"
      #     match:
      #       url: ".*"
      #     authenticators:
      #       - handler: jwt
      #     authorizer:
      #       handler: allow
      # domain:
      #   proxy: https://oathkeeper-proxy.ecoma.io
      #   api: https://oathkeeper-api.ecoma.io
      proxy:
        trust_forwarded_headers: true
        strip_path: true
        timeout:
          read: 5s
          write: 5s
          idle: 5s
        cors:
          enabled: false
          allowed_origins:
            - https://ecoma.io
            - https://*.ecoma.io
          allowed_methods:
            - GET
          allowed_headers:
            - ""
          exposed_headers:
            - ""
          allow_credentials: true
          max_age: -100000000
    deployment:
      nodeSelector: 
        kubernetes.io/hostname: node1
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: oathkeeper-secret
            key: dsn
  deployment:
    nodeSelector: 
      kubernetes.io/hostname: node1
  ingress:
    proxy:
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: oathkeeper-proxy.ecoma.io
          paths:
            - path: /
              pathType: Prefix
      tls:
      - hosts:
          - sentinel.ecoma.io
        secretName: oathkeeper-proxy-tls 
    api:
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: oathkeeper-api.ecoma.io
          paths:
            - path: /
              pathType: Prefix
      tls:
      - hosts:
          - sentinel-api.ecoma.io
        secretName: oathkeeper-api-tls 