kratosdb:
  fullnameOverride: kratosdb
  architecture: standalone
  auth:
    username: kratos  
    database: kratos
    existingSecret: postgresql-secret
    secretKeys:      
      userPasswordKey: password
      adminPasswordKey: admin-password
      replicationPasswordKey: replication-password
  primary:    
    nodeSelector: 
      kubernetes.io/hostname: node1
    persistence:
      size: 1Gi
      storageClass: local-path
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 768Mi
    initContainers:
      - name: wait-for-postgresql-secret
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            while [ ! -f /mnt/secrets/password ]; do
              echo "Waiting for postgresql-secret..."
              sleep 5
            done
            echo "postgresql-secret is ready!"
        volumeMounts:
          - name: postgresql-secret-volume
            mountPath: /mnt/secrets
            readOnly: true    
    extraVolumes:
      - name: postgresql-secret-volume
        secret:
          secretName: postgresql-secret

hydradb:
  fullnameOverride: hydradb
  architecture: standalone
  auth:
    username: hydra  
    database: hydra
    existingSecret: postgresql-secret
    secretKeys:      
      userPasswordKey: password
      adminPasswordKey: admin-password
      replicationPasswordKey: replication-password
  primary:    
    nodeSelector: 
      kubernetes.io/hostname: node1
    persistence:
      size: 1Gi
      storageClass: local-path
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 768Mi
    initContainers:
      - name: wait-for-postgresql-secret
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            while [ ! -f /mnt/secrets/password ]; do
              echo "Waiting for postgresql-secret..."
              sleep 5
            done
            echo "postgresql-secret is ready!"
        volumeMounts:
          - name: postgresql-secret-volume
            mountPath: /mnt/secrets
            readOnly: true    
    extraVolumes:
      - name: postgresql-secret-volume
        secret:
          secretName: postgresql-secret

kratos:
  fullnameOverride: kratos
  replicas: 1
  nodeSelector: 
    kubernetes.io/hostname: node1
  kratos:
    config:
      identity:
        default_schema_id: default
        schemas:
          - id: default
            url: file:///etc/config/identity.default.schema.json
      selfservice:
        default_browser_return_url: https://accounts.ecoma.io/
    automigration:
      enabled: true
    identitySchemas:
      "identity.default.schema.json": |
        {
          "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "Person",
          "type": "object",
          "properties": {
            "traits": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email",
                  "title": "E-Mail",
                  "ory.sh/kratos": {
                    "credentials": {
                      "password": {
                        "identifier": true
                      }
                    },
                    "recovery": {
                      "via": "email"
                    },
                    "verification": {
                      "via": "email"
                    }
                  }
                }
              },
              "required": [
                "email"
              ],
              "additionalProperties": false
            }
          }
        }
  deployment:
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: kratos-secret
            key: dsn
  statefulSet:
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: kratos-secret
            key: dsn
  job:
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: kratos-secret
            key: dsn
  cronjob:
    cleanup:
      extraEnv:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: kratos-secret
              key: dsn
  secret:
    enabled: false
    nameOverride: kratos-secret
  ingress:
    public:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: authenticate.ecoma.io
          paths:
            - path: /self-service/
              pathType: Prefix
      tls:
        - secretName: kratos-tls
          hosts:
            - authenticate.ecoma.io
    admin:
      enabled: true
      className: traefik      
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: authenticate.ecoma.io
          paths:
            - path: /admin/
              pathType: Prefix
      tls:
        - secretName: kratos-tls
          hosts:
            - authenticate.ecoma.io  
  extraInitContainers:
    - name: wait-for-postgresql
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL..."
          until nc -zv kratosdb 5432; do
            echo "PostgreSQL is not ready yet..."
            sleep 5
          done
          echo "PostgreSQL is ready!"

    - name: wait-for-secrets
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "Waiting for kratos-secret..."
          while [ ! -f /mnt/secrets/dsn ]; do
            echo "Secret kratos-secret not ready..."
            sleep 5
          done
          echo "kratos-secret is ready!"
      volumeMounts:
        - name: kratos-secret-volume
          mountPath: /mnt/secrets
          readOnly: true
  extraVolumes:
    - name: kratos-secret-volume
      secret:
        secretName: kratos-secret

kratosSelfserviceUiNode:
  fullnameOverride: accounts-ui
  config:
    csrfCookieName: __HOST-accounts.ecoma.io-x-csrf-token
  secret:
    enabled: false
    nameOverride: accounts-ui-secret
  kratosPublicUrl: "http://kratos-public.ory.svc.cluster.local"
  kratosAdminUrl: "http://kratos-admin.ory.svc.cluster.local"
  kratosBrowserUrl: "https://authenticate.ecoma.io"
  # jwksUrl: "http://oathkeeper-api"
  ingress:
    enabled: false
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: cluster-issuer
    hosts:
      - host: accounts.ecoma.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
        - accounts.ecoma.io
      secretName: accounts-ui-tls
  
hydraMaester:
  fullnameOverride: hydra-maester

  extraInitContainers:
    - name: wait-for-postgresql
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL..."
          until nc -zv hydrasdb 5432; do
            echo "PostgreSQL is not ready yet..."
            sleep 5
          done
          echo "PostgreSQL is ready!"

    - name: wait-for-secrets
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "Waiting for kratos-secret..."
          while [ ! -f /mnt/secrets/dsn ]; do
            echo "Secret kratos-secret not ready..."
            sleep 5
          done
          echo "hydra-secret is ready!"
      volumeMounts:
        - name: hydra-secret-volume
          mountPath: /mnt/secrets
          readOnly: true
  extraVolumes:
    - name: hydra-secret-volume
      secret:
        secretName: hydra-secret

hydra:
  fullnameOverride: hydra
  secret:
    enabled: false
    nameOverride: hydra-secret
  extraInitContainers:
    - name: wait-for-postgresql
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL..."
          until nc -zv hydrasdb 5432; do
            echo "PostgreSQL is not ready yet..."
            sleep 5
          done
          echo "PostgreSQL is ready!"

    - name: wait-for-secrets
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "Waiting for kratos-secret..."
          while [ ! -f /mnt/secrets/dsn ]; do
            echo "Secret kratos-secret not ready..."
            sleep 5
          done
          echo "hydra-secret is ready!"
      volumeMounts:
        - name: hydra-secret-volume
          mountPath: /mnt/secrets
          readOnly: true
  extraVolumes:
    - name: hydra-secret-volume
      secret:
        secretName: hydra-secret