---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql-secret
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AQBppMFeo6uv5T0feV/q5BSzFKldi0FjDscxGs0NXYQXn3X+iwZEqa3lt3lW0RivooyLEIkuM3MJKopYBFRKGPBpvtL2WJ4OwuqlSkaBWDOzCmA3JyX97/NP1Erpt4e1rvwZUiq7TvlBjjDH+cGD/jEkIqAIHDY3thYL2a1f1BqCTVPuC5hM97z9KZEZfCImSzQoJnp8SwaUct595nBgLNnL3ziTGMwzvv/eWedfdpuJAwEi7H8HpyRvCNpGxqgimCYS/HopZDdeZsj7YKGbc7Z0ubhSMcYM2qYMtPP3uGE2qZLAF8NUBtJbX2LajR2QFtN2BroD8NvxZKj3ULfNNm4bbQc0zomVz2pb++aSycW4Fd+8twya5XbxDQmhs6Xc6+H8QFDLpPYSe9dGndvf6exC
    password: AQBh9WzMtsRTbGFltV4FdyNrRAP+R2CZICqiV1qFJ+7Vy29Gg+ZIYxJb3ekbL7EyPhOvaDV6iIOiq8qbT8xpbbvg8XZ0/jCEHiJr8bdAN/1ZoHqiS5OVJA9/xRFT9P6+SxoB4JzCvP3+BoVpAV5+9mNuBbQ0wF1woQjf9xih1WZMNJg1U0nim2n2FEAyPCBPfJAlBNfgHgEPzQNwbJxiJthL+uBTwZq1pUqkaDgrwjCbwjxhM3HvEkTpsljsywzeGfpJf6UPYls9Q0LF+b6zNcP9V/UFRyS4gZCcdPI5+rERZga1dd3Os81/QtoT42lpH8ZZFMTlYFeHzBUm1tSt28YUXk7tzRpOUoX/63G53Cp4DaoIhXw8qs/rMdTm/p5xH0pr0Y9H4/YVcsnQfygRd1NX
    replication-password: AQAwfaj7H8v9SyS0IRaHnkQwitb4i+JnlCb56qDKO1KYJvnWVIIDxOYTFRVoin5tNPqw7I5rKd4wGZZaMEIjiUiR/jGotnPslLPGavk/S718dXWjFIcota0HJfYScXWqsAlv4AaZftxLMex9GWmXskOQ2gma1r66bSwz5chy7xOVUWnIAfoWRK2drFlrNq4E3W3EoQBZsF5VbFwwW0Ka3LMdLc8+VfkSGsr4Wi5o4MNkzfoHPcZqaQ//hB3cIzFZ+O//eitkMy7N3CZUO5K4J9oDkBjuo87PHp8WdEVoEloLjKTJHHfBjwJqU9R2H9ZZRl0wsvq1hkkQ0nPf1UonfAuH9dctuo4M1+cZyNL5ELxpz/4IWz36GzuKy+BTyCc9qKTujleduRXQ2C4MdDIqzy3R
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql-secret
      namespace: keycloak
    type: Opaque
